// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity_log.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAllActivityLogs = `-- name: CountAllActivityLogs :one
SELECT COUNT(*)
FROM activity_logs
WHERE ($1::text IS NULL OR event_type = $1)
  AND ($2::timestamptz IS NULL OR timestamp >= $2)
  AND ($3::timestamptz IS NULL OR timestamp < $3)
  AND ($4::uuid IS NULL OR app_id = $4::uuid)
`

type CountAllActivityLogsParams struct {
	EventType *string            `json:"event_type"`
	StartDate pgtype.Timestamptz `json:"start_date"`
	EndDate   pgtype.Timestamptz `json:"end_date"`
	AppID     pgtype.UUID        `json:"app_id"`
}

func (q *Queries) CountAllActivityLogs(ctx context.Context, arg CountAllActivityLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAllActivityLogs,
		arg.EventType,
		arg.StartDate,
		arg.EndDate,
		arg.AppID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserActivityLogs = `-- name: CountUserActivityLogs :one
SELECT COUNT(*)
FROM activity_logs
WHERE user_id = $1
  AND ($2::text IS NULL OR event_type = $2)
  AND ($3::timestamptz IS NULL OR timestamp >= $3)
  AND ($4::timestamptz IS NULL OR timestamp < $4)
`

type CountUserActivityLogsParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	EventType *string            `json:"event_type"`
	StartDate pgtype.Timestamptz `json:"start_date"`
	EndDate   pgtype.Timestamptz `json:"end_date"`
}

func (q *Queries) CountUserActivityLogs(ctx context.Context, arg CountUserActivityLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserActivityLogs,
		arg.UserID,
		arg.EventType,
		arg.StartDate,
		arg.EndDate,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createActivityLog = `-- name: CreateActivityLog :exec
INSERT INTO activity_logs (app_id, user_id, event_type, timestamp, ip_address, user_agent, details, severity, expires_at, is_anomaly)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateActivityLogParams struct {
	AppID     uuid.UUID          `json:"app_id"`
	UserID    uuid.UUID          `json:"user_id"`
	EventType string             `json:"event_type"`
	Timestamp time.Time          `json:"timestamp"`
	IpAddress string             `json:"ip_address"`
	UserAgent string             `json:"user_agent"`
	Details   []byte             `json:"details"`
	Severity  string             `json:"severity"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	IsAnomaly bool               `json:"is_anomaly"`
}

func (q *Queries) CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) error {
	_, err := q.db.Exec(ctx, createActivityLog,
		arg.AppID,
		arg.UserID,
		arg.EventType,
		arg.Timestamp,
		arg.IpAddress,
		arg.UserAgent,
		arg.Details,
		arg.Severity,
		arg.ExpiresAt,
		arg.IsAnomaly,
	)
	return err
}

const exportAllActivityLogs = `-- name: ExportAllActivityLogs :many
SELECT id, app_id, user_id, event_type, timestamp, ip_address, user_agent, details, severity, expires_at, is_anomaly
FROM activity_logs
WHERE ($1::text IS NULL OR event_type = $1)
  AND ($2::timestamptz IS NULL OR timestamp >= $2)
  AND ($3::timestamptz IS NULL OR timestamp < $3)
  AND ($4::uuid IS NULL OR app_id = $4::uuid)
ORDER BY timestamp DESC
LIMIT $5
`

type ExportAllActivityLogsParams struct {
	EventType *string            `json:"event_type"`
	StartDate pgtype.Timestamptz `json:"start_date"`
	EndDate   pgtype.Timestamptz `json:"end_date"`
	AppID     pgtype.UUID        `json:"app_id"`
	LimitVal  int32              `json:"limit_val"`
}

func (q *Queries) ExportAllActivityLogs(ctx context.Context, arg ExportAllActivityLogsParams) ([]ActivityLog, error) {
	rows, err := q.db.Query(ctx, exportAllActivityLogs,
		arg.EventType,
		arg.StartDate,
		arg.EndDate,
		arg.AppID,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityLog{}
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.UserID,
			&i.EventType,
			&i.Timestamp,
			&i.IpAddress,
			&i.UserAgent,
			&i.Details,
			&i.Severity,
			&i.ExpiresAt,
			&i.IsAnomaly,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportUserActivityLogs = `-- name: ExportUserActivityLogs :many
SELECT id, app_id, user_id, event_type, timestamp, ip_address, user_agent, details, severity, expires_at, is_anomaly
FROM activity_logs
WHERE user_id = $1
  AND ($2::text IS NULL OR event_type = $2)
  AND ($3::timestamptz IS NULL OR timestamp >= $3)
  AND ($4::timestamptz IS NULL OR timestamp < $4)
ORDER BY timestamp DESC
LIMIT $5
`

type ExportUserActivityLogsParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	EventType *string            `json:"event_type"`
	StartDate pgtype.Timestamptz `json:"start_date"`
	EndDate   pgtype.Timestamptz `json:"end_date"`
	LimitVal  int32              `json:"limit_val"`
}

func (q *Queries) ExportUserActivityLogs(ctx context.Context, arg ExportUserActivityLogsParams) ([]ActivityLog, error) {
	rows, err := q.db.Query(ctx, exportUserActivityLogs,
		arg.UserID,
		arg.EventType,
		arg.StartDate,
		arg.EndDate,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityLog{}
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.UserID,
			&i.EventType,
			&i.Timestamp,
			&i.IpAddress,
			&i.UserAgent,
			&i.Details,
			&i.Severity,
			&i.ExpiresAt,
			&i.IsAnomaly,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActivityLogByID = `-- name: GetActivityLogByID :one

SELECT id, app_id, user_id, event_type, timestamp, ip_address, user_agent, details, severity, expires_at, is_anomaly
FROM activity_logs
WHERE id = $1
`

// ============================================================================
// Activity log queries
// ============================================================================
func (q *Queries) GetActivityLogByID(ctx context.Context, id uuid.UUID) (ActivityLog, error) {
	row := q.db.QueryRow(ctx, getActivityLogByID, id)
	var i ActivityLog
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.UserID,
		&i.EventType,
		&i.Timestamp,
		&i.IpAddress,
		&i.UserAgent,
		&i.Details,
		&i.Severity,
		&i.ExpiresAt,
		&i.IsAnomaly,
	)
	return i, err
}

const listAllActivityLogs = `-- name: ListAllActivityLogs :many
SELECT id, app_id, user_id, event_type, timestamp, ip_address, user_agent, details, severity, expires_at, is_anomaly
FROM activity_logs
WHERE ($1::text IS NULL OR event_type = $1)
  AND ($2::timestamptz IS NULL OR timestamp >= $2)
  AND ($3::timestamptz IS NULL OR timestamp < $3)
  AND ($4::uuid IS NULL OR app_id = $4::uuid)
ORDER BY timestamp DESC
OFFSET $5 LIMIT $6
`

type ListAllActivityLogsParams struct {
	EventType *string            `json:"event_type"`
	StartDate pgtype.Timestamptz `json:"start_date"`
	EndDate   pgtype.Timestamptz `json:"end_date"`
	AppID     pgtype.UUID        `json:"app_id"`
	OffsetVal int32              `json:"offset_val"`
	LimitVal  int32              `json:"limit_val"`
}

func (q *Queries) ListAllActivityLogs(ctx context.Context, arg ListAllActivityLogsParams) ([]ActivityLog, error) {
	rows, err := q.db.Query(ctx, listAllActivityLogs,
		arg.EventType,
		arg.StartDate,
		arg.EndDate,
		arg.AppID,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityLog{}
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.UserID,
			&i.EventType,
			&i.Timestamp,
			&i.IpAddress,
			&i.UserAgent,
			&i.Details,
			&i.Severity,
			&i.ExpiresAt,
			&i.IsAnomaly,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserActivityLogs = `-- name: ListUserActivityLogs :many
SELECT id, app_id, user_id, event_type, timestamp, ip_address, user_agent, details, severity, expires_at, is_anomaly
FROM activity_logs
WHERE user_id = $1
  AND ($2::text IS NULL OR event_type = $2)
  AND ($3::timestamptz IS NULL OR timestamp >= $3)
  AND ($4::timestamptz IS NULL OR timestamp < $4)
ORDER BY timestamp DESC
OFFSET $5 LIMIT $6
`

type ListUserActivityLogsParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	EventType *string            `json:"event_type"`
	StartDate pgtype.Timestamptz `json:"start_date"`
	EndDate   pgtype.Timestamptz `json:"end_date"`
	OffsetVal int32              `json:"offset_val"`
	LimitVal  int32              `json:"limit_val"`
}

func (q *Queries) ListUserActivityLogs(ctx context.Context, arg ListUserActivityLogsParams) ([]ActivityLog, error) {
	rows, err := q.db.Query(ctx, listUserActivityLogs,
		arg.UserID,
		arg.EventType,
		arg.StartDate,
		arg.EndDate,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityLog{}
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.UserID,
			&i.EventType,
			&i.Timestamp,
			&i.IpAddress,
			&i.UserAgent,
			&i.Details,
			&i.Severity,
			&i.ExpiresAt,
			&i.IsAnomaly,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
