// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_account.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearAdminAccountBackupEmail = `-- name: ClearAdminAccountBackupEmail :exec
UPDATE admin_accounts
SET backup_email = '', backup_email_verified = FALSE, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ClearAdminAccountBackupEmail(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearAdminAccountBackupEmail, id)
	return err
}

const countAdminAccounts = `-- name: CountAdminAccounts :one
SELECT COUNT(*) FROM admin_accounts
`

func (q *Queries) CountAdminAccounts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminAccounts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEnabledSuperadminAccounts = `-- name: CountEnabledSuperadminAccounts :one
SELECT COUNT(*) FROM admin_accounts
WHERE operator_role_id = $1 AND disabled_at IS NULL AND app_id IS NULL
`

func (q *Queries) CountEnabledSuperadminAccounts(ctx context.Context, operatorRoleID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEnabledSuperadminAccounts, operatorRoleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdminAccount = `-- name: CreateAdminAccount :one
INSERT INTO admin_accounts (username, email, password_hash, operator_role_id, app_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, username, email, password_hash, operator_role_id, two_fa_enabled, two_fa_method, two_fa_secret, two_fa_recovery_codes, magic_link_enabled, backup_email, backup_email_verified, created_at, updated_at, last_login_at, disabled_at, app_id
`

type CreateAdminAccountParams struct {
	Username       string      `json:"username"`
	Email          *string     `json:"email"`
	PasswordHash   string      `json:"password_hash"`
	OperatorRoleID uuid.UUID   `json:"operator_role_id"`
	AppID          pgtype.UUID `json:"app_id"`
}

func (q *Queries) CreateAdminAccount(ctx context.Context, arg CreateAdminAccountParams) (AdminAccount, error) {
	row := q.db.QueryRow(ctx, createAdminAccount,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.OperatorRoleID,
		arg.AppID,
	)
	var i AdminAccount
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.OperatorRoleID,
		&i.TwoFaEnabled,
		&i.TwoFaMethod,
		&i.TwoFaSecret,
		&i.TwoFaRecoveryCodes,
		&i.MagicLinkEnabled,
		&i.BackupEmail,
		&i.BackupEmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.DisabledAt,
		&i.AppID,
	)
	return i, err
}

const deleteAdminAccountByID = `-- name: DeleteAdminAccountByID :exec
DELETE FROM admin_accounts
WHERE id = $1
`

func (q *Queries) DeleteAdminAccountByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAdminAccountByID, id)
	return err
}

const disableAdminAccount2FA = `-- name: DisableAdminAccount2FA :exec
UPDATE admin_accounts
SET two_fa_enabled = FALSE,
    two_fa_method = '',
    two_fa_secret = '',
    two_fa_recovery_codes = '[]',
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DisableAdminAccount2FA(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, disableAdminAccount2FA, id)
	return err
}

const enableAdminAccount2FA = `-- name: EnableAdminAccount2FA :exec
UPDATE admin_accounts
SET two_fa_enabled = TRUE,
    two_fa_method = $2,
    two_fa_secret = $3,
    two_fa_recovery_codes = $4,
    updated_at = NOW()
WHERE id = $1
`

type EnableAdminAccount2FAParams struct {
	ID                 uuid.UUID `json:"id"`
	TwoFaMethod        *string   `json:"two_fa_method"`
	TwoFaSecret        *string   `json:"two_fa_secret"`
	TwoFaRecoveryCodes []byte    `json:"two_fa_recovery_codes"`
}

func (q *Queries) EnableAdminAccount2FA(ctx context.Context, arg EnableAdminAccount2FAParams) error {
	_, err := q.db.Exec(ctx, enableAdminAccount2FA,
		arg.ID,
		arg.TwoFaMethod,
		arg.TwoFaSecret,
		arg.TwoFaRecoveryCodes,
	)
	return err
}

const getAdminAccountByEmail = `-- name: GetAdminAccountByEmail :one
SELECT id, username, email, password_hash, operator_role_id, two_fa_enabled, two_fa_method, two_fa_secret, two_fa_recovery_codes, magic_link_enabled, backup_email, backup_email_verified, created_at, updated_at, last_login_at, disabled_at, app_id FROM admin_accounts
WHERE email = $1
`

func (q *Queries) GetAdminAccountByEmail(ctx context.Context, email *string) (AdminAccount, error) {
	row := q.db.QueryRow(ctx, getAdminAccountByEmail, email)
	var i AdminAccount
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.OperatorRoleID,
		&i.TwoFaEnabled,
		&i.TwoFaMethod,
		&i.TwoFaSecret,
		&i.TwoFaRecoveryCodes,
		&i.MagicLinkEnabled,
		&i.BackupEmail,
		&i.BackupEmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.DisabledAt,
		&i.AppID,
	)
	return i, err
}

const getAdminAccountByID = `-- name: GetAdminAccountByID :one
SELECT id, username, email, password_hash, operator_role_id, two_fa_enabled, two_fa_method, two_fa_secret, two_fa_recovery_codes, magic_link_enabled, backup_email, backup_email_verified, created_at, updated_at, last_login_at, disabled_at, app_id FROM admin_accounts
WHERE id = $1
`

func (q *Queries) GetAdminAccountByID(ctx context.Context, id uuid.UUID) (AdminAccount, error) {
	row := q.db.QueryRow(ctx, getAdminAccountByID, id)
	var i AdminAccount
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.OperatorRoleID,
		&i.TwoFaEnabled,
		&i.TwoFaMethod,
		&i.TwoFaSecret,
		&i.TwoFaRecoveryCodes,
		&i.MagicLinkEnabled,
		&i.BackupEmail,
		&i.BackupEmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.DisabledAt,
		&i.AppID,
	)
	return i, err
}

const getAdminAccountByUsername = `-- name: GetAdminAccountByUsername :one
SELECT id, username, email, password_hash, operator_role_id, two_fa_enabled, two_fa_method, two_fa_secret, two_fa_recovery_codes, magic_link_enabled, backup_email, backup_email_verified, created_at, updated_at, last_login_at, disabled_at, app_id FROM admin_accounts
WHERE username = $1
`

func (q *Queries) GetAdminAccountByUsername(ctx context.Context, username string) (AdminAccount, error) {
	row := q.db.QueryRow(ctx, getAdminAccountByUsername, username)
	var i AdminAccount
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.OperatorRoleID,
		&i.TwoFaEnabled,
		&i.TwoFaMethod,
		&i.TwoFaSecret,
		&i.TwoFaRecoveryCodes,
		&i.MagicLinkEnabled,
		&i.BackupEmail,
		&i.BackupEmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.DisabledAt,
		&i.AppID,
	)
	return i, err
}

const getAdminAccountByUsernameOrEmail = `-- name: GetAdminAccountByUsernameOrEmail :one
SELECT id, username, email, password_hash, operator_role_id, two_fa_enabled, two_fa_method, two_fa_secret, two_fa_recovery_codes, magic_link_enabled, backup_email, backup_email_verified, created_at, updated_at, last_login_at, disabled_at, app_id FROM admin_accounts
WHERE username = $1 OR email = $1
`

func (q *Queries) GetAdminAccountByUsernameOrEmail(ctx context.Context, username string) (AdminAccount, error) {
	row := q.db.QueryRow(ctx, getAdminAccountByUsernameOrEmail, username)
	var i AdminAccount
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.OperatorRoleID,
		&i.TwoFaEnabled,
		&i.TwoFaMethod,
		&i.TwoFaSecret,
		&i.TwoFaRecoveryCodes,
		&i.MagicLinkEnabled,
		&i.BackupEmail,
		&i.BackupEmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.DisabledAt,
		&i.AppID,
	)
	return i, err
}

const listAllAdminAccounts = `-- name: ListAllAdminAccounts :many
SELECT id, username, email, password_hash, operator_role_id, two_fa_enabled, two_fa_method, two_fa_secret, two_fa_recovery_codes, magic_link_enabled, backup_email, backup_email_verified, created_at, updated_at, last_login_at, disabled_at, app_id FROM admin_accounts
ORDER BY created_at ASC
`

func (q *Queries) ListAllAdminAccounts(ctx context.Context) ([]AdminAccount, error) {
	rows, err := q.db.Query(ctx, listAllAdminAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminAccount{}
	for rows.Next() {
		var i AdminAccount
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.OperatorRoleID,
			&i.TwoFaEnabled,
			&i.TwoFaMethod,
			&i.TwoFaSecret,
			&i.TwoFaRecoveryCodes,
			&i.MagicLinkEnabled,
			&i.BackupEmail,
			&i.BackupEmailVerified,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
			&i.DisabledAt,
			&i.AppID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAdminAccountBackupEmail = `-- name: SetAdminAccountBackupEmail :exec
UPDATE admin_accounts
SET backup_email = $2, backup_email_verified = FALSE, updated_at = NOW()
WHERE id = $1
`

type SetAdminAccountBackupEmailParams struct {
	ID          uuid.UUID `json:"id"`
	BackupEmail string    `json:"backup_email"`
}

func (q *Queries) SetAdminAccountBackupEmail(ctx context.Context, arg SetAdminAccountBackupEmailParams) error {
	_, err := q.db.Exec(ctx, setAdminAccountBackupEmail, arg.ID, arg.BackupEmail)
	return err
}

const setAdminAccountDisabledAt = `-- name: SetAdminAccountDisabledAt :exec
UPDATE admin_accounts
SET disabled_at = $2, updated_at = NOW()
WHERE id = $1
`

type SetAdminAccountDisabledAtParams struct {
	ID         uuid.UUID          `json:"id"`
	DisabledAt pgtype.Timestamptz `json:"disabled_at"`
}

func (q *Queries) SetAdminAccountDisabledAt(ctx context.Context, arg SetAdminAccountDisabledAtParams) error {
	_, err := q.db.Exec(ctx, setAdminAccountDisabledAt, arg.ID, arg.DisabledAt)
	return err
}

const updateAdminAccountAppID = `-- name: UpdateAdminAccountAppID :exec
UPDATE admin_accounts
SET app_id = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateAdminAccountAppIDParams struct {
	ID    uuid.UUID   `json:"id"`
	AppID pgtype.UUID `json:"app_id"`
}

func (q *Queries) UpdateAdminAccountAppID(ctx context.Context, arg UpdateAdminAccountAppIDParams) error {
	_, err := q.db.Exec(ctx, updateAdminAccountAppID, arg.ID, arg.AppID)
	return err
}

const updateAdminAccountEmail = `-- name: UpdateAdminAccountEmail :exec
UPDATE admin_accounts
SET email = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateAdminAccountEmailParams struct {
	ID    uuid.UUID `json:"id"`
	Email *string   `json:"email"`
}

func (q *Queries) UpdateAdminAccountEmail(ctx context.Context, arg UpdateAdminAccountEmailParams) error {
	_, err := q.db.Exec(ctx, updateAdminAccountEmail, arg.ID, arg.Email)
	return err
}

const updateAdminAccountLastLogin = `-- name: UpdateAdminAccountLastLogin :exec
UPDATE admin_accounts
SET last_login_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateAdminAccountLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateAdminAccountLastLogin, id)
	return err
}

const updateAdminAccountMagicLinkEnabled = `-- name: UpdateAdminAccountMagicLinkEnabled :exec
UPDATE admin_accounts
SET magic_link_enabled = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateAdminAccountMagicLinkEnabledParams struct {
	ID               uuid.UUID `json:"id"`
	MagicLinkEnabled bool      `json:"magic_link_enabled"`
}

func (q *Queries) UpdateAdminAccountMagicLinkEnabled(ctx context.Context, arg UpdateAdminAccountMagicLinkEnabledParams) error {
	_, err := q.db.Exec(ctx, updateAdminAccountMagicLinkEnabled, arg.ID, arg.MagicLinkEnabled)
	return err
}

const updateAdminAccountOperatorRole = `-- name: UpdateAdminAccountOperatorRole :exec
UPDATE admin_accounts
SET operator_role_id = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateAdminAccountOperatorRoleParams struct {
	ID             uuid.UUID `json:"id"`
	OperatorRoleID uuid.UUID `json:"operator_role_id"`
}

func (q *Queries) UpdateAdminAccountOperatorRole(ctx context.Context, arg UpdateAdminAccountOperatorRoleParams) error {
	_, err := q.db.Exec(ctx, updateAdminAccountOperatorRole, arg.ID, arg.OperatorRoleID)
	return err
}

const updateAdminAccountPassword = `-- name: UpdateAdminAccountPassword :exec
UPDATE admin_accounts
SET password_hash = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateAdminAccountPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateAdminAccountPassword(ctx context.Context, arg UpdateAdminAccountPasswordParams) error {
	_, err := q.db.Exec(ctx, updateAdminAccountPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateAdminAccountRecoveryCodes = `-- name: UpdateAdminAccountRecoveryCodes :exec
UPDATE admin_accounts
SET two_fa_recovery_codes = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateAdminAccountRecoveryCodesParams struct {
	ID                 uuid.UUID `json:"id"`
	TwoFaRecoveryCodes []byte    `json:"two_fa_recovery_codes"`
}

func (q *Queries) UpdateAdminAccountRecoveryCodes(ctx context.Context, arg UpdateAdminAccountRecoveryCodesParams) error {
	_, err := q.db.Exec(ctx, updateAdminAccountRecoveryCodes, arg.ID, arg.TwoFaRecoveryCodes)
	return err
}
