// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bruteforce.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearUserLockout = `-- name: ClearUserLockout :exec
UPDATE users
SET locked_at = NULL,
    lock_reason = '',
    lock_expires_at = NULL,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ClearUserLockout(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearUserLockout, id)
	return err
}

const lockUserByEmail = `-- name: LockUserByEmail :execrows
UPDATE users
SET locked_at = $1,
    lock_reason = $2,
    lock_expires_at = $3,
    updated_at = NOW()
WHERE app_id = $4 AND email = $5
`

type LockUserByEmailParams struct {
	LockedAt      pgtype.Timestamptz `json:"locked_at"`
	LockReason    string             `json:"lock_reason"`
	LockExpiresAt pgtype.Timestamptz `json:"lock_expires_at"`
	AppID         uuid.UUID          `json:"app_id"`
	Email         string             `json:"email"`
}

func (q *Queries) LockUserByEmail(ctx context.Context, arg LockUserByEmailParams) (int64, error) {
	result, err := q.db.Exec(ctx, lockUserByEmail,
		arg.LockedAt,
		arg.LockReason,
		arg.LockExpiresAt,
		arg.AppID,
		arg.Email,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
