// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearDefaultFlagByApp = `-- name: ClearDefaultFlagByApp :exec
UPDATE email_server_configs SET is_default = FALSE WHERE app_id = $1
`

func (q *Queries) ClearDefaultFlagByApp(ctx context.Context, appID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearDefaultFlagByApp, appID)
	return err
}

const clearDefaultFlagGlobal = `-- name: ClearDefaultFlagGlobal :exec
UPDATE email_server_configs SET is_default = FALSE WHERE app_id IS NULL
`

func (q *Queries) ClearDefaultFlagGlobal(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearDefaultFlagGlobal)
	return err
}

const createEmailType = `-- name: CreateEmailType :exec
INSERT INTO email_types (
    id, code, name, description, default_subject, variables, is_system, is_active, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
`

type CreateEmailTypeParams struct {
	ID             uuid.UUID `json:"id"`
	Code           string    `json:"code"`
	Name           string    `json:"name"`
	Description    *string   `json:"description"`
	DefaultSubject *string   `json:"default_subject"`
	Variables      []byte    `json:"variables"`
	IsSystem       bool      `json:"is_system"`
	IsActive       bool      `json:"is_active"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) CreateEmailType(ctx context.Context, arg CreateEmailTypeParams) error {
	_, err := q.db.Exec(ctx, createEmailType,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.DefaultSubject,
		arg.Variables,
		arg.IsSystem,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createServerConfig = `-- name: CreateServerConfig :exec
INSERT INTO email_server_configs (
    id, app_id, name, smtp_host, smtp_port, smtp_username, smtp_password,
    from_address, from_name, use_tls, is_active, is_default, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12, $13, $14
)
`

type CreateServerConfigParams struct {
	ID           uuid.UUID   `json:"id"`
	AppID        pgtype.UUID `json:"app_id"`
	Name         string      `json:"name"`
	SmtpHost     string      `json:"smtp_host"`
	SmtpPort     int32       `json:"smtp_port"`
	SmtpUsername *string     `json:"smtp_username"`
	SmtpPassword *string     `json:"smtp_password"`
	FromAddress  string      `json:"from_address"`
	FromName     *string     `json:"from_name"`
	UseTls       bool        `json:"use_tls"`
	IsActive     bool        `json:"is_active"`
	IsDefault    bool        `json:"is_default"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

func (q *Queries) CreateServerConfig(ctx context.Context, arg CreateServerConfigParams) error {
	_, err := q.db.Exec(ctx, createServerConfig,
		arg.ID,
		arg.AppID,
		arg.Name,
		arg.SmtpHost,
		arg.SmtpPort,
		arg.SmtpUsername,
		arg.SmtpPassword,
		arg.FromAddress,
		arg.FromName,
		arg.UseTls,
		arg.IsActive,
		arg.IsDefault,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createTemplate = `-- name: CreateTemplate :exec
INSERT INTO email_templates (
    id, app_id, email_type_id, server_config_id, name, subject,
    body_html, body_text, from_email, from_name, template_engine, is_active, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12, $13, $14
)
`

type CreateTemplateParams struct {
	ID             uuid.UUID   `json:"id"`
	AppID          pgtype.UUID `json:"app_id"`
	EmailTypeID    uuid.UUID   `json:"email_type_id"`
	ServerConfigID pgtype.UUID `json:"server_config_id"`
	Name           string      `json:"name"`
	Subject        string      `json:"subject"`
	BodyHtml       *string     `json:"body_html"`
	BodyText       *string     `json:"body_text"`
	FromEmail      *string     `json:"from_email"`
	FromName       *string     `json:"from_name"`
	TemplateEngine string      `json:"template_engine"`
	IsActive       bool        `json:"is_active"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) error {
	_, err := q.db.Exec(ctx, createTemplate,
		arg.ID,
		arg.AppID,
		arg.EmailTypeID,
		arg.ServerConfigID,
		arg.Name,
		arg.Subject,
		arg.BodyHtml,
		arg.BodyText,
		arg.FromEmail,
		arg.FromName,
		arg.TemplateEngine,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteNonSystemEmailType = `-- name: DeleteNonSystemEmailType :execrows
DELETE FROM email_types WHERE id = $1 AND is_system = FALSE
`

func (q *Queries) DeleteNonSystemEmailType(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNonSystemEmailType, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteServerConfigByApp = `-- name: DeleteServerConfigByApp :exec
DELETE FROM email_server_configs WHERE app_id = $1
`

func (q *Queries) DeleteServerConfigByApp(ctx context.Context, appID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteServerConfigByApp, appID)
	return err
}

const deleteServerConfigByID = `-- name: DeleteServerConfigByID :exec
DELETE FROM email_server_configs WHERE id = $1
`

func (q *Queries) DeleteServerConfigByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteServerConfigByID, id)
	return err
}

const deleteTemplateByID = `-- name: DeleteTemplateByID :exec
DELETE FROM email_templates WHERE id = $1
`

func (q *Queries) DeleteTemplateByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTemplateByID, id)
	return err
}

const deleteTemplatesByEmailTypeID = `-- name: DeleteTemplatesByEmailTypeID :exec
DELETE FROM email_templates WHERE email_type_id = $1
`

func (q *Queries) DeleteTemplatesByEmailTypeID(ctx context.Context, emailTypeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTemplatesByEmailTypeID, emailTypeID)
	return err
}

const getActiveEmailTypes = `-- name: GetActiveEmailTypes :many
SELECT id, code, name, description, default_subject, variables, is_system, is_active, created_at, updated_at
FROM email_types
WHERE is_active = TRUE
ORDER BY name ASC
`

func (q *Queries) GetActiveEmailTypes(ctx context.Context) ([]EmailType, error) {
	rows, err := q.db.Query(ctx, getActiveEmailTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailType{}
	for rows.Next() {
		var i EmailType
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.DefaultSubject,
			&i.Variables,
			&i.IsSystem,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllEmailTypes = `-- name: GetAllEmailTypes :many

SELECT id, code, name, description, default_subject, variables, is_system, is_active, created_at, updated_at
FROM email_types
ORDER BY name ASC
`

// ============================================================================
// Email Type queries
// ============================================================================
func (q *Queries) GetAllEmailTypes(ctx context.Context) ([]EmailType, error) {
	rows, err := q.db.Query(ctx, getAllEmailTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailType{}
	for rows.Next() {
		var i EmailType
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.DefaultSubject,
			&i.Variables,
			&i.IsSystem,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllServerConfigs = `-- name: GetAllServerConfigs :many
SELECT id, app_id, name, smtp_host, smtp_port, smtp_username, smtp_password,
       from_address, from_name, use_tls, is_active, is_default, created_at, updated_at
FROM email_server_configs
ORDER BY app_id IS NOT NULL, app_id, is_default DESC, name ASC
`

func (q *Queries) GetAllServerConfigs(ctx context.Context) ([]EmailServerConfig, error) {
	rows, err := q.db.Query(ctx, getAllServerConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailServerConfig{}
	for rows.Next() {
		var i EmailServerConfig
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.Name,
			&i.SmtpHost,
			&i.SmtpPort,
			&i.SmtpUsername,
			&i.SmtpPassword,
			&i.FromAddress,
			&i.FromName,
			&i.UseTls,
			&i.IsActive,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEmailTypeByCode = `-- name: GetEmailTypeByCode :one
SELECT id, code, name, description, default_subject, variables, is_system, is_active, created_at, updated_at
FROM email_types
WHERE code = $1
`

func (q *Queries) GetEmailTypeByCode(ctx context.Context, code string) (EmailType, error) {
	row := q.db.QueryRow(ctx, getEmailTypeByCode, code)
	var i EmailType
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.DefaultSubject,
		&i.Variables,
		&i.IsSystem,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmailTypeByID = `-- name: GetEmailTypeByID :one
SELECT id, code, name, description, default_subject, variables, is_system, is_active, created_at, updated_at
FROM email_types
WHERE id = $1
`

func (q *Queries) GetEmailTypeByID(ctx context.Context, id uuid.UUID) (EmailType, error) {
	row := q.db.QueryRow(ctx, getEmailTypeByID, id)
	var i EmailType
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.DefaultSubject,
		&i.Variables,
		&i.IsSystem,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGlobalDefaultTemplates = `-- name: GetGlobalDefaultTemplates :many
SELECT t.id, t.app_id, t.email_type_id, t.server_config_id, t.name, t.subject,
       t.body_html, t.body_text, t.from_email, t.from_name, t.template_engine, t.is_active,
       t.created_at, t.updated_at,
       et.id AS et_id, et.code AS et_code, et.name AS et_name, et.description AS et_description,
       et.default_subject AS et_default_subject, et.variables AS et_variables,
       et.is_system AS et_is_system, et.is_active AS et_is_active,
       et.created_at AS et_created_at, et.updated_at AS et_updated_at
FROM email_templates t
JOIN email_types et ON et.id = t.email_type_id
WHERE t.app_id IS NULL
ORDER BY t.created_at ASC
`

type GetGlobalDefaultTemplatesRow struct {
	ID               uuid.UUID   `json:"id"`
	AppID            pgtype.UUID `json:"app_id"`
	EmailTypeID      uuid.UUID   `json:"email_type_id"`
	ServerConfigID   pgtype.UUID `json:"server_config_id"`
	Name             string      `json:"name"`
	Subject          string      `json:"subject"`
	BodyHtml         *string     `json:"body_html"`
	BodyText         *string     `json:"body_text"`
	FromEmail        *string     `json:"from_email"`
	FromName         *string     `json:"from_name"`
	TemplateEngine   string      `json:"template_engine"`
	IsActive         bool        `json:"is_active"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
	EtID             uuid.UUID   `json:"et_id"`
	EtCode           string      `json:"et_code"`
	EtName           string      `json:"et_name"`
	EtDescription    *string     `json:"et_description"`
	EtDefaultSubject *string     `json:"et_default_subject"`
	EtVariables      []byte      `json:"et_variables"`
	EtIsSystem       bool        `json:"et_is_system"`
	EtIsActive       bool        `json:"et_is_active"`
	EtCreatedAt      time.Time   `json:"et_created_at"`
	EtUpdatedAt      time.Time   `json:"et_updated_at"`
}

func (q *Queries) GetGlobalDefaultTemplates(ctx context.Context) ([]GetGlobalDefaultTemplatesRow, error) {
	rows, err := q.db.Query(ctx, getGlobalDefaultTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGlobalDefaultTemplatesRow{}
	for rows.Next() {
		var i GetGlobalDefaultTemplatesRow
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.EmailTypeID,
			&i.ServerConfigID,
			&i.Name,
			&i.Subject,
			&i.BodyHtml,
			&i.BodyText,
			&i.FromEmail,
			&i.FromName,
			&i.TemplateEngine,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EtID,
			&i.EtCode,
			&i.EtName,
			&i.EtDescription,
			&i.EtDefaultSubject,
			&i.EtVariables,
			&i.EtIsSystem,
			&i.EtIsActive,
			&i.EtCreatedAt,
			&i.EtUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGlobalServerConfigActiveAny = `-- name: GetGlobalServerConfigActiveAny :one
SELECT id, app_id, name, smtp_host, smtp_port, smtp_username, smtp_password,
       from_address, from_name, use_tls, is_active, is_default, created_at, updated_at
FROM email_server_configs
WHERE app_id IS NULL AND is_active = TRUE
LIMIT 1
`

func (q *Queries) GetGlobalServerConfigActiveAny(ctx context.Context) (EmailServerConfig, error) {
	row := q.db.QueryRow(ctx, getGlobalServerConfigActiveAny)
	var i EmailServerConfig
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Name,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SmtpUsername,
		&i.SmtpPassword,
		&i.FromAddress,
		&i.FromName,
		&i.UseTls,
		&i.IsActive,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGlobalServerConfigActiveDefault = `-- name: GetGlobalServerConfigActiveDefault :one
SELECT id, app_id, name, smtp_host, smtp_port, smtp_username, smtp_password,
       from_address, from_name, use_tls, is_active, is_default, created_at, updated_at
FROM email_server_configs
WHERE app_id IS NULL AND is_active = TRUE AND is_default = TRUE
LIMIT 1
`

func (q *Queries) GetGlobalServerConfigActiveDefault(ctx context.Context) (EmailServerConfig, error) {
	row := q.db.QueryRow(ctx, getGlobalServerConfigActiveDefault)
	var i EmailServerConfig
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Name,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SmtpUsername,
		&i.SmtpPassword,
		&i.FromAddress,
		&i.FromName,
		&i.UseTls,
		&i.IsActive,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServerConfigActiveAny = `-- name: GetServerConfigActiveAny :one
SELECT id, app_id, name, smtp_host, smtp_port, smtp_username, smtp_password,
       from_address, from_name, use_tls, is_active, is_default, created_at, updated_at
FROM email_server_configs
WHERE app_id = $1 AND is_active = TRUE
LIMIT 1
`

func (q *Queries) GetServerConfigActiveAny(ctx context.Context, appID pgtype.UUID) (EmailServerConfig, error) {
	row := q.db.QueryRow(ctx, getServerConfigActiveAny, appID)
	var i EmailServerConfig
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Name,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SmtpUsername,
		&i.SmtpPassword,
		&i.FromAddress,
		&i.FromName,
		&i.UseTls,
		&i.IsActive,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServerConfigActiveDefault = `-- name: GetServerConfigActiveDefault :one

SELECT id, app_id, name, smtp_host, smtp_port, smtp_username, smtp_password,
       from_address, from_name, use_tls, is_active, is_default, created_at, updated_at
FROM email_server_configs
WHERE app_id = $1 AND is_active = TRUE AND is_default = TRUE
LIMIT 1
`

// ============================================================================
// Email Server Config queries
// ============================================================================
func (q *Queries) GetServerConfigActiveDefault(ctx context.Context, appID pgtype.UUID) (EmailServerConfig, error) {
	row := q.db.QueryRow(ctx, getServerConfigActiveDefault, appID)
	var i EmailServerConfig
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Name,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SmtpUsername,
		&i.SmtpPassword,
		&i.FromAddress,
		&i.FromName,
		&i.UseTls,
		&i.IsActive,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServerConfigAnyByApp = `-- name: GetServerConfigAnyByApp :one
SELECT id, app_id, name, smtp_host, smtp_port, smtp_username, smtp_password,
       from_address, from_name, use_tls, is_active, is_default, created_at, updated_at
FROM email_server_configs
WHERE app_id = $1
LIMIT 1
`

func (q *Queries) GetServerConfigAnyByApp(ctx context.Context, appID pgtype.UUID) (EmailServerConfig, error) {
	row := q.db.QueryRow(ctx, getServerConfigAnyByApp, appID)
	var i EmailServerConfig
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Name,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SmtpUsername,
		&i.SmtpPassword,
		&i.FromAddress,
		&i.FromName,
		&i.UseTls,
		&i.IsActive,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServerConfigByID = `-- name: GetServerConfigByID :one
SELECT id, app_id, name, smtp_host, smtp_port, smtp_username, smtp_password,
       from_address, from_name, use_tls, is_active, is_default, created_at, updated_at
FROM email_server_configs
WHERE id = $1
`

func (q *Queries) GetServerConfigByID(ctx context.Context, id uuid.UUID) (EmailServerConfig, error) {
	row := q.db.QueryRow(ctx, getServerConfigByID, id)
	var i EmailServerConfig
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Name,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SmtpUsername,
		&i.SmtpPassword,
		&i.FromAddress,
		&i.FromName,
		&i.UseTls,
		&i.IsActive,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServerConfigsByApp = `-- name: GetServerConfigsByApp :many
SELECT id, app_id, name, smtp_host, smtp_port, smtp_username, smtp_password,
       from_address, from_name, use_tls, is_active, is_default, created_at, updated_at
FROM email_server_configs
WHERE app_id = $1
ORDER BY is_default DESC, name ASC
`

func (q *Queries) GetServerConfigsByApp(ctx context.Context, appID pgtype.UUID) ([]EmailServerConfig, error) {
	rows, err := q.db.Query(ctx, getServerConfigsByApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailServerConfig{}
	for rows.Next() {
		var i EmailServerConfig
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.Name,
			&i.SmtpHost,
			&i.SmtpPort,
			&i.SmtpUsername,
			&i.SmtpPassword,
			&i.FromAddress,
			&i.FromName,
			&i.UseTls,
			&i.IsActive,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTemplateByAppAndType = `-- name: GetTemplateByAppAndType :one

SELECT id, app_id, email_type_id, server_config_id, name, subject,
       body_html, body_text, from_email, from_name, template_engine, is_active, created_at, updated_at
FROM email_templates
WHERE app_id = $1 AND email_type_id = $2 AND is_active = TRUE
LIMIT 1
`

type GetTemplateByAppAndTypeParams struct {
	AppID       pgtype.UUID `json:"app_id"`
	EmailTypeID uuid.UUID   `json:"email_type_id"`
}

// ============================================================================
// Email Template queries
// ============================================================================
func (q *Queries) GetTemplateByAppAndType(ctx context.Context, arg GetTemplateByAppAndTypeParams) (EmailTemplate, error) {
	row := q.db.QueryRow(ctx, getTemplateByAppAndType, arg.AppID, arg.EmailTypeID)
	var i EmailTemplate
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.EmailTypeID,
		&i.ServerConfigID,
		&i.Name,
		&i.Subject,
		&i.BodyHtml,
		&i.BodyText,
		&i.FromEmail,
		&i.FromName,
		&i.TemplateEngine,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplateByAppAndTypeID = `-- name: GetTemplateByAppAndTypeID :one
SELECT id, app_id, email_type_id, server_config_id, name, subject,
       body_html, body_text, from_email, from_name, template_engine, is_active, created_at, updated_at
FROM email_templates
WHERE app_id = $1 AND email_type_id = $2
LIMIT 1
`

type GetTemplateByAppAndTypeIDParams struct {
	AppID       pgtype.UUID `json:"app_id"`
	EmailTypeID uuid.UUID   `json:"email_type_id"`
}

func (q *Queries) GetTemplateByAppAndTypeID(ctx context.Context, arg GetTemplateByAppAndTypeIDParams) (EmailTemplate, error) {
	row := q.db.QueryRow(ctx, getTemplateByAppAndTypeID, arg.AppID, arg.EmailTypeID)
	var i EmailTemplate
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.EmailTypeID,
		&i.ServerConfigID,
		&i.Name,
		&i.Subject,
		&i.BodyHtml,
		&i.BodyText,
		&i.FromEmail,
		&i.FromName,
		&i.TemplateEngine,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplateByID = `-- name: GetTemplateByID :one
SELECT t.id, t.app_id, t.email_type_id, t.server_config_id, t.name, t.subject,
       t.body_html, t.body_text, t.from_email, t.from_name, t.template_engine, t.is_active,
       t.created_at, t.updated_at,
       et.id AS et_id, et.code AS et_code, et.name AS et_name, et.description AS et_description,
       et.default_subject AS et_default_subject, et.variables AS et_variables,
       et.is_system AS et_is_system, et.is_active AS et_is_active,
       et.created_at AS et_created_at, et.updated_at AS et_updated_at
FROM email_templates t
JOIN email_types et ON et.id = t.email_type_id
WHERE t.id = $1
`

type GetTemplateByIDRow struct {
	ID               uuid.UUID   `json:"id"`
	AppID            pgtype.UUID `json:"app_id"`
	EmailTypeID      uuid.UUID   `json:"email_type_id"`
	ServerConfigID   pgtype.UUID `json:"server_config_id"`
	Name             string      `json:"name"`
	Subject          string      `json:"subject"`
	BodyHtml         *string     `json:"body_html"`
	BodyText         *string     `json:"body_text"`
	FromEmail        *string     `json:"from_email"`
	FromName         *string     `json:"from_name"`
	TemplateEngine   string      `json:"template_engine"`
	IsActive         bool        `json:"is_active"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
	EtID             uuid.UUID   `json:"et_id"`
	EtCode           string      `json:"et_code"`
	EtName           string      `json:"et_name"`
	EtDescription    *string     `json:"et_description"`
	EtDefaultSubject *string     `json:"et_default_subject"`
	EtVariables      []byte      `json:"et_variables"`
	EtIsSystem       bool        `json:"et_is_system"`
	EtIsActive       bool        `json:"et_is_active"`
	EtCreatedAt      time.Time   `json:"et_created_at"`
	EtUpdatedAt      time.Time   `json:"et_updated_at"`
}

func (q *Queries) GetTemplateByID(ctx context.Context, id uuid.UUID) (GetTemplateByIDRow, error) {
	row := q.db.QueryRow(ctx, getTemplateByID, id)
	var i GetTemplateByIDRow
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.EmailTypeID,
		&i.ServerConfigID,
		&i.Name,
		&i.Subject,
		&i.BodyHtml,
		&i.BodyText,
		&i.FromEmail,
		&i.FromName,
		&i.TemplateEngine,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EtID,
		&i.EtCode,
		&i.EtName,
		&i.EtDescription,
		&i.EtDefaultSubject,
		&i.EtVariables,
		&i.EtIsSystem,
		&i.EtIsActive,
		&i.EtCreatedAt,
		&i.EtUpdatedAt,
	)
	return i, err
}

const getTemplateGlobalByType = `-- name: GetTemplateGlobalByType :one
SELECT id, app_id, email_type_id, server_config_id, name, subject,
       body_html, body_text, from_email, from_name, template_engine, is_active, created_at, updated_at
FROM email_templates
WHERE app_id IS NULL AND email_type_id = $1 AND is_active = TRUE
LIMIT 1
`

func (q *Queries) GetTemplateGlobalByType(ctx context.Context, emailTypeID uuid.UUID) (EmailTemplate, error) {
	row := q.db.QueryRow(ctx, getTemplateGlobalByType, emailTypeID)
	var i EmailTemplate
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.EmailTypeID,
		&i.ServerConfigID,
		&i.Name,
		&i.Subject,
		&i.BodyHtml,
		&i.BodyText,
		&i.FromEmail,
		&i.FromName,
		&i.TemplateEngine,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplateGlobalByTypeID = `-- name: GetTemplateGlobalByTypeID :one
SELECT id, app_id, email_type_id, server_config_id, name, subject,
       body_html, body_text, from_email, from_name, template_engine, is_active, created_at, updated_at
FROM email_templates
WHERE app_id IS NULL AND email_type_id = $1
LIMIT 1
`

func (q *Queries) GetTemplateGlobalByTypeID(ctx context.Context, emailTypeID uuid.UUID) (EmailTemplate, error) {
	row := q.db.QueryRow(ctx, getTemplateGlobalByTypeID, emailTypeID)
	var i EmailTemplate
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.EmailTypeID,
		&i.ServerConfigID,
		&i.Name,
		&i.Subject,
		&i.BodyHtml,
		&i.BodyText,
		&i.FromEmail,
		&i.FromName,
		&i.TemplateEngine,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplatesByApp = `-- name: GetTemplatesByApp :many
SELECT t.id, t.app_id, t.email_type_id, t.server_config_id, t.name, t.subject,
       t.body_html, t.body_text, t.from_email, t.from_name, t.template_engine, t.is_active,
       t.created_at, t.updated_at,
       et.id AS et_id, et.code AS et_code, et.name AS et_name, et.description AS et_description,
       et.default_subject AS et_default_subject, et.variables AS et_variables,
       et.is_system AS et_is_system, et.is_active AS et_is_active,
       et.created_at AS et_created_at, et.updated_at AS et_updated_at
FROM email_templates t
JOIN email_types et ON et.id = t.email_type_id
WHERE t.app_id = $1
ORDER BY t.created_at ASC
`

type GetTemplatesByAppRow struct {
	ID               uuid.UUID   `json:"id"`
	AppID            pgtype.UUID `json:"app_id"`
	EmailTypeID      uuid.UUID   `json:"email_type_id"`
	ServerConfigID   pgtype.UUID `json:"server_config_id"`
	Name             string      `json:"name"`
	Subject          string      `json:"subject"`
	BodyHtml         *string     `json:"body_html"`
	BodyText         *string     `json:"body_text"`
	FromEmail        *string     `json:"from_email"`
	FromName         *string     `json:"from_name"`
	TemplateEngine   string      `json:"template_engine"`
	IsActive         bool        `json:"is_active"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
	EtID             uuid.UUID   `json:"et_id"`
	EtCode           string      `json:"et_code"`
	EtName           string      `json:"et_name"`
	EtDescription    *string     `json:"et_description"`
	EtDefaultSubject *string     `json:"et_default_subject"`
	EtVariables      []byte      `json:"et_variables"`
	EtIsSystem       bool        `json:"et_is_system"`
	EtIsActive       bool        `json:"et_is_active"`
	EtCreatedAt      time.Time   `json:"et_created_at"`
	EtUpdatedAt      time.Time   `json:"et_updated_at"`
}

func (q *Queries) GetTemplatesByApp(ctx context.Context, appID pgtype.UUID) ([]GetTemplatesByAppRow, error) {
	rows, err := q.db.Query(ctx, getTemplatesByApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTemplatesByAppRow{}
	for rows.Next() {
		var i GetTemplatesByAppRow
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.EmailTypeID,
			&i.ServerConfigID,
			&i.Name,
			&i.Subject,
			&i.BodyHtml,
			&i.BodyText,
			&i.FromEmail,
			&i.FromName,
			&i.TemplateEngine,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EtID,
			&i.EtCode,
			&i.EtName,
			&i.EtDescription,
			&i.EtDefaultSubject,
			&i.EtVariables,
			&i.EtIsSystem,
			&i.EtIsActive,
			&i.EtCreatedAt,
			&i.EtUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllActiveServerConfigs = `-- name: ListAllActiveServerConfigs :many
SELECT id, app_id, name, smtp_host, smtp_port, smtp_username, smtp_password,
       from_address, from_name, use_tls, is_active, is_default, created_at, updated_at
FROM email_server_configs
WHERE is_active = TRUE
ORDER BY is_default DESC, created_at ASC
`

func (q *Queries) ListAllActiveServerConfigs(ctx context.Context) ([]EmailServerConfig, error) {
	rows, err := q.db.Query(ctx, listAllActiveServerConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailServerConfig{}
	for rows.Next() {
		var i EmailServerConfig
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.Name,
			&i.SmtpHost,
			&i.SmtpPort,
			&i.SmtpUsername,
			&i.SmtpPassword,
			&i.FromAddress,
			&i.FromName,
			&i.UseTls,
			&i.IsActive,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmailType = `-- name: UpdateEmailType :exec
UPDATE email_types
SET code            = $2,
    name            = $3,
    description     = $4,
    default_subject = $5,
    variables       = $6,
    is_system       = $7,
    is_active       = $8,
    updated_at      = $9
WHERE id = $1
`

type UpdateEmailTypeParams struct {
	ID             uuid.UUID `json:"id"`
	Code           string    `json:"code"`
	Name           string    `json:"name"`
	Description    *string   `json:"description"`
	DefaultSubject *string   `json:"default_subject"`
	Variables      []byte    `json:"variables"`
	IsSystem       bool      `json:"is_system"`
	IsActive       bool      `json:"is_active"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) UpdateEmailType(ctx context.Context, arg UpdateEmailTypeParams) error {
	_, err := q.db.Exec(ctx, updateEmailType,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.DefaultSubject,
		arg.Variables,
		arg.IsSystem,
		arg.IsActive,
		arg.UpdatedAt,
	)
	return err
}

const updateServerConfig = `-- name: UpdateServerConfig :exec
UPDATE email_server_configs
SET app_id        = $2,
    name          = $3,
    smtp_host     = $4,
    smtp_port     = $5,
    smtp_username = $6,
    smtp_password = $7,
    from_address  = $8,
    from_name     = $9,
    use_tls       = $10,
    is_active     = $11,
    is_default    = $12,
    updated_at    = $13
WHERE id = $1
`

type UpdateServerConfigParams struct {
	ID           uuid.UUID   `json:"id"`
	AppID        pgtype.UUID `json:"app_id"`
	Name         string      `json:"name"`
	SmtpHost     string      `json:"smtp_host"`
	SmtpPort     int32       `json:"smtp_port"`
	SmtpUsername *string     `json:"smtp_username"`
	SmtpPassword *string     `json:"smtp_password"`
	FromAddress  string      `json:"from_address"`
	FromName     *string     `json:"from_name"`
	UseTls       bool        `json:"use_tls"`
	IsActive     bool        `json:"is_active"`
	IsDefault    bool        `json:"is_default"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

func (q *Queries) UpdateServerConfig(ctx context.Context, arg UpdateServerConfigParams) error {
	_, err := q.db.Exec(ctx, updateServerConfig,
		arg.ID,
		arg.AppID,
		arg.Name,
		arg.SmtpHost,
		arg.SmtpPort,
		arg.SmtpUsername,
		arg.SmtpPassword,
		arg.FromAddress,
		arg.FromName,
		arg.UseTls,
		arg.IsActive,
		arg.IsDefault,
		arg.UpdatedAt,
	)
	return err
}

const updateTemplate = `-- name: UpdateTemplate :exec
UPDATE email_templates
SET app_id           = $2,
    email_type_id    = $3,
    server_config_id = $4,
    name             = $5,
    subject          = $6,
    body_html        = $7,
    body_text        = $8,
    from_email       = $9,
    from_name        = $10,
    template_engine  = $11,
    is_active        = $12,
    updated_at       = $13
WHERE id = $1
`

type UpdateTemplateParams struct {
	ID             uuid.UUID   `json:"id"`
	AppID          pgtype.UUID `json:"app_id"`
	EmailTypeID    uuid.UUID   `json:"email_type_id"`
	ServerConfigID pgtype.UUID `json:"server_config_id"`
	Name           string      `json:"name"`
	Subject        string      `json:"subject"`
	BodyHtml       *string     `json:"body_html"`
	BodyText       *string     `json:"body_text"`
	FromEmail      *string     `json:"from_email"`
	FromName       *string     `json:"from_name"`
	TemplateEngine string      `json:"template_engine"`
	IsActive       bool        `json:"is_active"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) error {
	_, err := q.db.Exec(ctx, updateTemplate,
		arg.ID,
		arg.AppID,
		arg.EmailTypeID,
		arg.ServerConfigID,
		arg.Name,
		arg.Subject,
		arg.BodyHtml,
		arg.BodyText,
		arg.FromEmail,
		arg.FromName,
		arg.TemplateEngine,
		arg.IsActive,
		arg.UpdatedAt,
	)
	return err
}
