// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ActivityLog struct {
	ID        uuid.UUID          `json:"id"`
	AppID     uuid.UUID          `json:"app_id"`
	UserID    uuid.UUID          `json:"user_id"`
	EventType string             `json:"event_type"`
	Timestamp time.Time          `json:"timestamp"`
	IpAddress string             `json:"ip_address"`
	UserAgent string             `json:"user_agent"`
	Details   []byte             `json:"details"`
	Severity  string             `json:"severity"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	IsAnomaly bool               `json:"is_anomaly"`
}

type AdminAccount struct {
	ID                  uuid.UUID          `json:"id"`
	Username            string             `json:"username"`
	Email               *string            `json:"email"`
	PasswordHash        string             `json:"password_hash"`
	OperatorRoleID      uuid.UUID          `json:"operator_role_id"`
	TwoFaEnabled        bool               `json:"two_fa_enabled"`
	TwoFaMethod         *string            `json:"two_fa_method"`
	TwoFaSecret         *string            `json:"two_fa_secret"`
	TwoFaRecoveryCodes  []byte             `json:"two_fa_recovery_codes"`
	MagicLinkEnabled    bool               `json:"magic_link_enabled"`
	BackupEmail         string             `json:"backup_email"`
	BackupEmailVerified bool               `json:"backup_email_verified"`
	CreatedAt           time.Time          `json:"created_at"`
	UpdatedAt           time.Time          `json:"updated_at"`
	LastLoginAt         pgtype.Timestamptz `json:"last_login_at"`
	DisabledAt          pgtype.Timestamptz `json:"disabled_at"`
	AppID               pgtype.UUID        `json:"app_id"`
}

type ApiKey struct {
	ID              uuid.UUID          `json:"id"`
	KeyType         string             `json:"key_type"`
	Name            string             `json:"name"`
	Description     string             `json:"description"`
	KeyHash         string             `json:"key_hash"`
	KeyPrefix       string             `json:"key_prefix"`
	KeySuffix       string             `json:"key_suffix"`
	AppID           pgtype.UUID        `json:"app_id"`
	Scopes          string             `json:"scopes"`
	OperatorRoleID  pgtype.UUID        `json:"operator_role_id"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt      pgtype.Timestamptz `json:"last_used_at"`
	Notified7DaysAt pgtype.Timestamptz `json:"notified_7_days_at"`
	Notified1DayAt  pgtype.Timestamptz `json:"notified_1_day_at"`
	IsRevoked       bool               `json:"is_revoked"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

type ApiKeyUsage struct {
	ID           int64       `json:"id"`
	ApiKeyID     uuid.UUID   `json:"api_key_id"`
	PeriodDate   pgtype.Date `json:"period_date"`
	RequestCount int64       `json:"request_count"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

type Application struct {
	ID                        uuid.UUID `json:"id"`
	TenantID                  uuid.UUID `json:"tenant_id"`
	Name                      string    `json:"name"`
	Description               *string   `json:"description"`
	TwoFaIssuerName           string    `json:"two_fa_issuer_name"`
	TwoFaEnabled              bool      `json:"two_fa_enabled"`
	TwoFaRequired             bool      `json:"two_fa_required"`
	Email2faEnabled           bool      `json:"email_2fa_enabled"`
	TwoFaMethods              string    `json:"two_fa_methods"`
	Passkey2faEnabled         bool      `json:"passkey_2fa_enabled"`
	PasskeyLoginEnabled       bool      `json:"passkey_login_enabled"`
	MagicLinkEnabled          bool      `json:"magic_link_enabled"`
	LoginNotificationsEnabled bool      `json:"login_notifications_enabled"`
	SuspiciousActivityAlerts  bool      `json:"suspicious_activity_alerts"`
	Sms2faEnabled             bool      `json:"sms_2fa_enabled"`
	TrustedDeviceEnabled      bool      `json:"trusted_device_enabled"`
	TrustedDeviceMaxDays      int32     `json:"trusted_device_max_days"`
	BfLockoutEnabled          *bool     `json:"bf_lockout_enabled"`
	BfLockoutThreshold        *int32    `json:"bf_lockout_threshold"`
	BfLockoutDurations        *string   `json:"bf_lockout_durations"`
	BfLockoutWindow           *string   `json:"bf_lockout_window"`
	BfLockoutTierTtl          *string   `json:"bf_lockout_tier_ttl"`
	BfDelayEnabled            *bool     `json:"bf_delay_enabled"`
	BfDelayStartAfter         *int32    `json:"bf_delay_start_after"`
	BfDelayMaxSeconds         *int32    `json:"bf_delay_max_seconds"`
	BfDelayTierTtl            *string   `json:"bf_delay_tier_ttl"`
	BfCaptchaEnabled          *bool     `json:"bf_captcha_enabled"`
	BfCaptchaSiteKey          *string   `json:"bf_captcha_site_key"`
	BfCaptchaSecretKey        *string   `json:"bf_captcha_secret_key"`
	BfCaptchaThreshold        *int32    `json:"bf_captcha_threshold"`
	OidcEnabled               bool      `json:"oidc_enabled"`
	OidcRsaPrivateKey         string    `json:"oidc_rsa_private_key"`
	OidcIDTokenTtl            int32     `json:"oidc_id_token_ttl"`
	OidcIssuerUrl             string    `json:"oidc_issuer_url"`
	FrontendUrl               string    `json:"frontend_url"`
	LoginLogoUrl              string    `json:"login_logo_url"`
	LoginTheme                string    `json:"login_theme"`
	LoginPrimaryColor         string    `json:"login_primary_color"`
	LoginSecondaryColor       string    `json:"login_secondary_color"`
	LoginDisplayName          string    `json:"login_display_name"`
	PwMinLength               int32     `json:"pw_min_length"`
	PwMaxLength               int32     `json:"pw_max_length"`
	PwRequireUpper            bool      `json:"pw_require_upper"`
	PwRequireLower            bool      `json:"pw_require_lower"`
	PwRequireDigit            bool      `json:"pw_require_digit"`
	PwRequireSymbol           bool      `json:"pw_require_symbol"`
	PwHistoryCount            int32     `json:"pw_history_count"`
	PwMaxAgeDays              int32     `json:"pw_max_age_days"`
	AccessTokenTtlMinutes     int32     `json:"access_token_ttl_minutes"`
	RefreshTokenTtlHours      int32     `json:"refresh_token_ttl_hours"`
	ResetPasswordPath         string    `json:"reset_password_path"`
	MagicLinkPath             string    `json:"magic_link_path"`
	VerifyEmailPath           string    `json:"verify_email_path"`
	CreatedAt                 time.Time `json:"created_at"`
	UpdatedAt                 time.Time `json:"updated_at"`
}

type EmailServerConfig struct {
	ID           uuid.UUID   `json:"id"`
	AppID        pgtype.UUID `json:"app_id"`
	Name         string      `json:"name"`
	SmtpHost     string      `json:"smtp_host"`
	SmtpPort     int32       `json:"smtp_port"`
	SmtpUsername *string     `json:"smtp_username"`
	SmtpPassword *string     `json:"smtp_password"`
	FromAddress  string      `json:"from_address"`
	FromName     *string     `json:"from_name"`
	UseTls       bool        `json:"use_tls"`
	IsActive     bool        `json:"is_active"`
	IsDefault    bool        `json:"is_default"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

type EmailTemplate struct {
	ID             uuid.UUID   `json:"id"`
	AppID          pgtype.UUID `json:"app_id"`
	EmailTypeID    uuid.UUID   `json:"email_type_id"`
	ServerConfigID pgtype.UUID `json:"server_config_id"`
	Name           string      `json:"name"`
	Subject        string      `json:"subject"`
	BodyHtml       *string     `json:"body_html"`
	BodyText       *string     `json:"body_text"`
	FromEmail      *string     `json:"from_email"`
	FromName       *string     `json:"from_name"`
	TemplateEngine string      `json:"template_engine"`
	IsActive       bool        `json:"is_active"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

type EmailType struct {
	ID             uuid.UUID `json:"id"`
	Code           string    `json:"code"`
	Name           string    `json:"name"`
	Description    *string   `json:"description"`
	DefaultSubject *string   `json:"default_subject"`
	Variables      []byte    `json:"variables"`
	IsSystem       bool      `json:"is_system"`
	IsActive       bool      `json:"is_active"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type IpRule struct {
	ID          uuid.UUID `json:"id"`
	AppID       uuid.UUID `json:"app_id"`
	RuleType    string    `json:"rule_type"`
	MatchType   string    `json:"match_type"`
	Value       string    `json:"value"`
	Description string    `json:"description"`
	IsActive    bool      `json:"is_active"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type OauthProviderConfig struct {
	ID           uuid.UUID `json:"id"`
	AppID        uuid.UUID `json:"app_id"`
	Provider     string    `json:"provider"`
	ClientID     string    `json:"client_id"`
	ClientSecret string    `json:"client_secret"`
	RedirectUrl  string    `json:"redirect_url"`
	IsEnabled    bool      `json:"is_enabled"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type OidcAuthCode struct {
	ID                  uuid.UUID `json:"id"`
	AppID               uuid.UUID `json:"app_id"`
	ClientID            string    `json:"client_id"`
	UserID              uuid.UUID `json:"user_id"`
	Code                string    `json:"code"`
	RedirectUri         string    `json:"redirect_uri"`
	Scopes              string    `json:"scopes"`
	Nonce               string    `json:"nonce"`
	CodeChallenge       string    `json:"code_challenge"`
	CodeChallengeMethod string    `json:"code_challenge_method"`
	ExpiresAt           time.Time `json:"expires_at"`
	Used                bool      `json:"used"`
	CreatedAt           time.Time `json:"created_at"`
}

type OidcClient struct {
	ID                uuid.UUID `json:"id"`
	AppID             uuid.UUID `json:"app_id"`
	Name              string    `json:"name"`
	Description       string    `json:"description"`
	ClientID          string    `json:"client_id"`
	ClientSecretHash  string    `json:"client_secret_hash"`
	RedirectUris      string    `json:"redirect_uris"`
	AllowedGrantTypes string    `json:"allowed_grant_types"`
	AllowedScopes     string    `json:"allowed_scopes"`
	RequireConsent    bool      `json:"require_consent"`
	IsConfidential    bool      `json:"is_confidential"`
	PkceRequired      bool      `json:"pkce_required"`
	IsActive          bool      `json:"is_active"`
	LogoUrl           string    `json:"logo_url"`
	LoginTheme        string    `json:"login_theme"`
	LoginPrimaryColor string    `json:"login_primary_color"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type OperatorAccessLog struct {
	ID        uuid.UUID   `json:"id"`
	At        time.Time   `json:"at"`
	Kind      string      `json:"kind"`
	KeyID     pgtype.UUID `json:"key_id"`
	AccountID pgtype.UUID `json:"account_id"`
	RoleName  string      `json:"role_name"`
	Method    string      `json:"method"`
	Path      string      `json:"path"`
	Decision  string      `json:"decision"`
	Resource  string      `json:"resource"`
	Action    string      `json:"action"`
	Status    int32       `json:"status"`
	IpAddress string      `json:"ip_address"`
	UserAgent string      `json:"user_agent"`
}

type OperatorIamEvent struct {
	ID              uuid.UUID   `json:"id"`
	At              time.Time   `json:"at"`
	ActorKind       string      `json:"actor_kind"`
	ActorKeyID      pgtype.UUID `json:"actor_key_id"`
	ActorAccountID  pgtype.UUID `json:"actor_account_id"`
	TargetKind      string      `json:"target_kind"`
	TargetKeyID     pgtype.UUID `json:"target_key_id"`
	TargetAccountID pgtype.UUID `json:"target_account_id"`
	OldRoleID       pgtype.UUID `json:"old_role_id"`
	NewRoleID       pgtype.UUID `json:"new_role_id"`
	Action          string      `json:"action"`
}

type OperatorPermission struct {
	ID          uuid.UUID `json:"id"`
	Resource    string    `json:"resource"`
	Action      string    `json:"action"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
}

type OperatorRole struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	IsSystem    bool      `json:"is_system"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type OperatorRolePermission struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

type Permission struct {
	ID          uuid.UUID `json:"id"`
	Resource    string    `json:"resource"`
	Action      string    `json:"action"`
	Description *string   `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
}

type Role struct {
	ID          uuid.UUID `json:"id"`
	AppID       uuid.UUID `json:"app_id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	IsSystem    bool      `json:"is_system"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type RolePermission struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

type SchemaMigration struct {
	ID              int32     `json:"id"`
	Version         string    `json:"version"`
	Name            string    `json:"name"`
	AppliedAt       time.Time `json:"applied_at"`
	ExecutionTimeMs *int32    `json:"execution_time_ms"`
	Success         bool      `json:"success"`
	ErrorMessage    *string   `json:"error_message"`
	Checksum        *string   `json:"checksum"`
}

type SessionGroup struct {
	ID           uuid.UUID `json:"id"`
	TenantID     uuid.UUID `json:"tenant_id"`
	Name         string    `json:"name"`
	Description  string    `json:"description"`
	GlobalLogout bool      `json:"global_logout"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type SessionGroupApp struct {
	SessionGroupID uuid.UUID `json:"session_group_id"`
	AppID          uuid.UUID `json:"app_id"`
	AddedAt        time.Time `json:"added_at"`
}

type SocialAccount struct {
	ID             uuid.UUID          `json:"id"`
	AppID          uuid.UUID          `json:"app_id"`
	UserID         uuid.UUID          `json:"user_id"`
	Provider       string             `json:"provider"`
	ProviderUserID string             `json:"provider_user_id"`
	Email          string             `json:"email"`
	Name           string             `json:"name"`
	FirstName      string             `json:"first_name"`
	LastName       string             `json:"last_name"`
	ProfilePicture string             `json:"profile_picture"`
	Username       string             `json:"username"`
	Locale         string             `json:"locale"`
	RawData        []byte             `json:"raw_data"`
	AccessToken    string             `json:"access_token"`
	RefreshToken   string             `json:"refresh_token"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
}

type SystemSetting struct {
	Key       string    `json:"key"`
	Value     string    `json:"value"`
	Category  string    `json:"category"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Tenant struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type TrustedDevice struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	AppID      uuid.UUID `json:"app_id"`
	TokenHash  string    `json:"token_hash"`
	Name       *string   `json:"name"`
	UserAgent  *string   `json:"user_agent"`
	IpAddress  *string   `json:"ip_address"`
	LastUsedAt time.Time `json:"last_used_at"`
	ExpiresAt  time.Time `json:"expires_at"`
	CreatedAt  time.Time `json:"created_at"`
}

type User struct {
	ID                  uuid.UUID          `json:"id"`
	AppID               uuid.UUID          `json:"app_id"`
	Email               string             `json:"email"`
	PasswordHash        string             `json:"password_hash"`
	EmailVerified       bool               `json:"email_verified"`
	IsActive            bool               `json:"is_active"`
	Name                string             `json:"name"`
	FirstName           string             `json:"first_name"`
	LastName            string             `json:"last_name"`
	ProfilePicture      string             `json:"profile_picture"`
	Locale              string             `json:"locale"`
	TwoFaEnabled        bool               `json:"two_fa_enabled"`
	TwoFaMethod         string             `json:"two_fa_method"`
	TwoFaSecret         string             `json:"two_fa_secret"`
	TwoFaRecoveryCodes  json.RawMessage    `json:"two_fa_recovery_codes"`
	BackupEmail         string             `json:"backup_email"`
	BackupEmailVerified bool               `json:"backup_email_verified"`
	TwoFaPreviousMethod string             `json:"two_fa_previous_method"`
	TwoFaPreviousSecret string             `json:"two_fa_previous_secret"`
	PhoneNumber         string             `json:"phone_number"`
	PhoneVerified       bool               `json:"phone_verified"`
	LockedAt            pgtype.Timestamptz `json:"locked_at"`
	LockReason          string             `json:"lock_reason"`
	LockExpiresAt       pgtype.Timestamptz `json:"lock_expires_at"`
	PasswordHistory     []byte             `json:"password_history"`
	PasswordChangedAt   pgtype.Timestamptz `json:"password_changed_at"`
	CreatedAt           time.Time          `json:"created_at"`
	UpdatedAt           time.Time          `json:"updated_at"`
}

type UserRole struct {
	UserID     uuid.UUID   `json:"user_id"`
	RoleID     uuid.UUID   `json:"role_id"`
	AppID      uuid.UUID   `json:"app_id"`
	AssignedAt time.Time   `json:"assigned_at"`
	AssignedBy pgtype.UUID `json:"assigned_by"`
}

type WebauthnCredential struct {
	ID              uuid.UUID          `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	AppID           pgtype.UUID        `json:"app_id"`
	AdminID         pgtype.UUID        `json:"admin_id"`
	CredentialID    []byte             `json:"credential_id"`
	PublicKey       []byte             `json:"public_key"`
	AttestationType *string            `json:"attestation_type"`
	Aaguid          []byte             `json:"aaguid"`
	SignCount       int32              `json:"sign_count"`
	Name            *string            `json:"name"`
	Transports      *string            `json:"transports"`
	BackupEligible  bool               `json:"backup_eligible"`
	BackupState     bool               `json:"backup_state"`
	LastUsedAt      pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt       time.Time          `json:"created_at"`
}

type WebhookDelivery struct {
	ID           uuid.UUID          `json:"id"`
	EndpointID   uuid.UUID          `json:"endpoint_id"`
	AppID        uuid.UUID          `json:"app_id"`
	EventType    string             `json:"event_type"`
	Payload      string             `json:"payload"`
	Attempt      int32              `json:"attempt"`
	StatusCode   *int32             `json:"status_code"`
	ResponseBody *string            `json:"response_body"`
	LatencyMs    *int64             `json:"latency_ms"`
	Success      bool               `json:"success"`
	ErrorMessage *string            `json:"error_message"`
	NextRetryAt  pgtype.Timestamptz `json:"next_retry_at"`
	CreatedAt    time.Time          `json:"created_at"`
}

type WebhookEndpoint struct {
	ID        uuid.UUID          `json:"id"`
	AppID     uuid.UUID          `json:"app_id"`
	EventType string             `json:"event_type"`
	Url       string             `json:"url"`
	Secret    string             `json:"secret"`
	IsActive  bool               `json:"is_active"`
	CreatedAt time.Time          `json:"created_at"`
	UpdatedAt time.Time          `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}
