// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oidc.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createOIDCAuthCode = `-- name: CreateOIDCAuthCode :exec
INSERT INTO oidc_auth_codes (
    id, app_id, client_id, user_id, code, redirect_uri,
    scopes, nonce, code_challenge, code_challenge_method,
    expires_at, used, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10,
    $11, $12, $13
)
`

type CreateOIDCAuthCodeParams struct {
	ID                  uuid.UUID `json:"id"`
	AppID               uuid.UUID `json:"app_id"`
	ClientID            string    `json:"client_id"`
	UserID              uuid.UUID `json:"user_id"`
	Code                string    `json:"code"`
	RedirectUri         string    `json:"redirect_uri"`
	Scopes              string    `json:"scopes"`
	Nonce               string    `json:"nonce"`
	CodeChallenge       string    `json:"code_challenge"`
	CodeChallengeMethod string    `json:"code_challenge_method"`
	ExpiresAt           time.Time `json:"expires_at"`
	Used                bool      `json:"used"`
	CreatedAt           time.Time `json:"created_at"`
}

func (q *Queries) CreateOIDCAuthCode(ctx context.Context, arg CreateOIDCAuthCodeParams) error {
	_, err := q.db.Exec(ctx, createOIDCAuthCode,
		arg.ID,
		arg.AppID,
		arg.ClientID,
		arg.UserID,
		arg.Code,
		arg.RedirectUri,
		arg.Scopes,
		arg.Nonce,
		arg.CodeChallenge,
		arg.CodeChallengeMethod,
		arg.ExpiresAt,
		arg.Used,
		arg.CreatedAt,
	)
	return err
}

const createOIDCClient = `-- name: CreateOIDCClient :exec
INSERT INTO oidc_clients (
    id, app_id, name, description, client_id, client_secret_hash,
    redirect_uris, allowed_grant_types, allowed_scopes,
    require_consent, is_confidential, pkce_required, is_active,
    logo_url, login_theme, login_primary_color,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12, $13,
    $14, $15, $16,
    $17, $18
)
`

type CreateOIDCClientParams struct {
	ID                uuid.UUID `json:"id"`
	AppID             uuid.UUID `json:"app_id"`
	Name              string    `json:"name"`
	Description       string    `json:"description"`
	ClientID          string    `json:"client_id"`
	ClientSecretHash  string    `json:"client_secret_hash"`
	RedirectUris      string    `json:"redirect_uris"`
	AllowedGrantTypes string    `json:"allowed_grant_types"`
	AllowedScopes     string    `json:"allowed_scopes"`
	RequireConsent    bool      `json:"require_consent"`
	IsConfidential    bool      `json:"is_confidential"`
	PkceRequired      bool      `json:"pkce_required"`
	IsActive          bool      `json:"is_active"`
	LogoUrl           string    `json:"logo_url"`
	LoginTheme        string    `json:"login_theme"`
	LoginPrimaryColor string    `json:"login_primary_color"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

func (q *Queries) CreateOIDCClient(ctx context.Context, arg CreateOIDCClientParams) error {
	_, err := q.db.Exec(ctx, createOIDCClient,
		arg.ID,
		arg.AppID,
		arg.Name,
		arg.Description,
		arg.ClientID,
		arg.ClientSecretHash,
		arg.RedirectUris,
		arg.AllowedGrantTypes,
		arg.AllowedScopes,
		arg.RequireConsent,
		arg.IsConfidential,
		arg.PkceRequired,
		arg.IsActive,
		arg.LogoUrl,
		arg.LoginTheme,
		arg.LoginPrimaryColor,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteExpiredOIDCAuthCodes = `-- name: DeleteExpiredOIDCAuthCodes :exec
DELETE FROM oidc_auth_codes
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredOIDCAuthCodes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredOIDCAuthCodes)
	return err
}

const deleteOIDCClient = `-- name: DeleteOIDCClient :exec
DELETE FROM oidc_clients
WHERE id = $1
`

func (q *Queries) DeleteOIDCClient(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOIDCClient, id)
	return err
}

const getApplicationForOIDC = `-- name: GetApplicationForOIDC :one
SELECT id, tenant_id, name, description,
       two_fa_issuer_name, two_fa_enabled, two_fa_required, email_2fa_enabled, two_fa_methods,
       passkey_2fa_enabled, passkey_login_enabled,
       magic_link_enabled,
       login_notifications_enabled, suspicious_activity_alerts,
       sms_2fa_enabled,
       trusted_device_enabled, trusted_device_max_days,
       bf_lockout_enabled, bf_lockout_threshold, bf_lockout_durations, bf_lockout_window, bf_lockout_tier_ttl,
       bf_delay_enabled, bf_delay_start_after, bf_delay_max_seconds, bf_delay_tier_ttl,
       bf_captcha_enabled, bf_captcha_site_key, bf_captcha_secret_key, bf_captcha_threshold,
       oidc_enabled, oidc_rsa_private_key, oidc_id_token_ttl, oidc_issuer_url,
       frontend_url,
       login_logo_url, login_theme, login_primary_color, login_secondary_color, login_display_name,
       pw_min_length, pw_max_length, pw_require_upper, pw_require_lower, pw_require_digit, pw_require_symbol,
       pw_history_count, pw_max_age_days,
       access_token_ttl_minutes, refresh_token_ttl_hours,
       reset_password_path, magic_link_path, verify_email_path,
       created_at, updated_at
FROM applications
WHERE id = $1
`

func (q *Queries) GetApplicationForOIDC(ctx context.Context, id uuid.UUID) (Application, error) {
	row := q.db.QueryRow(ctx, getApplicationForOIDC, id)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.TwoFaIssuerName,
		&i.TwoFaEnabled,
		&i.TwoFaRequired,
		&i.Email2faEnabled,
		&i.TwoFaMethods,
		&i.Passkey2faEnabled,
		&i.PasskeyLoginEnabled,
		&i.MagicLinkEnabled,
		&i.LoginNotificationsEnabled,
		&i.SuspiciousActivityAlerts,
		&i.Sms2faEnabled,
		&i.TrustedDeviceEnabled,
		&i.TrustedDeviceMaxDays,
		&i.BfLockoutEnabled,
		&i.BfLockoutThreshold,
		&i.BfLockoutDurations,
		&i.BfLockoutWindow,
		&i.BfLockoutTierTtl,
		&i.BfDelayEnabled,
		&i.BfDelayStartAfter,
		&i.BfDelayMaxSeconds,
		&i.BfDelayTierTtl,
		&i.BfCaptchaEnabled,
		&i.BfCaptchaSiteKey,
		&i.BfCaptchaSecretKey,
		&i.BfCaptchaThreshold,
		&i.OidcEnabled,
		&i.OidcRsaPrivateKey,
		&i.OidcIDTokenTtl,
		&i.OidcIssuerUrl,
		&i.FrontendUrl,
		&i.LoginLogoUrl,
		&i.LoginTheme,
		&i.LoginPrimaryColor,
		&i.LoginSecondaryColor,
		&i.LoginDisplayName,
		&i.PwMinLength,
		&i.PwMaxLength,
		&i.PwRequireUpper,
		&i.PwRequireLower,
		&i.PwRequireDigit,
		&i.PwRequireSymbol,
		&i.PwHistoryCount,
		&i.PwMaxAgeDays,
		&i.AccessTokenTtlMinutes,
		&i.RefreshTokenTtlHours,
		&i.ResetPasswordPath,
		&i.MagicLinkPath,
		&i.VerifyEmailPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOIDCAuthCode = `-- name: GetOIDCAuthCode :one
SELECT id, app_id, client_id, user_id, code, redirect_uri,
       scopes, nonce, code_challenge, code_challenge_method,
       expires_at, used, created_at
FROM oidc_auth_codes
WHERE code = $1
`

func (q *Queries) GetOIDCAuthCode(ctx context.Context, code string) (OidcAuthCode, error) {
	row := q.db.QueryRow(ctx, getOIDCAuthCode, code)
	var i OidcAuthCode
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.ClientID,
		&i.UserID,
		&i.Code,
		&i.RedirectUri,
		&i.Scopes,
		&i.Nonce,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const getOIDCClientByClientID = `-- name: GetOIDCClientByClientID :one
SELECT id, app_id, name, description, client_id, client_secret_hash,
       redirect_uris, allowed_grant_types, allowed_scopes,
       require_consent, is_confidential, pkce_required, is_active,
       logo_url, login_theme, login_primary_color,
       created_at, updated_at
FROM oidc_clients
WHERE client_id = $1
`

func (q *Queries) GetOIDCClientByClientID(ctx context.Context, clientID string) (OidcClient, error) {
	row := q.db.QueryRow(ctx, getOIDCClientByClientID, clientID)
	var i OidcClient
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Name,
		&i.Description,
		&i.ClientID,
		&i.ClientSecretHash,
		&i.RedirectUris,
		&i.AllowedGrantTypes,
		&i.AllowedScopes,
		&i.RequireConsent,
		&i.IsConfidential,
		&i.PkceRequired,
		&i.IsActive,
		&i.LogoUrl,
		&i.LoginTheme,
		&i.LoginPrimaryColor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOIDCClientByID = `-- name: GetOIDCClientByID :one
SELECT id, app_id, name, description, client_id, client_secret_hash,
       redirect_uris, allowed_grant_types, allowed_scopes,
       require_consent, is_confidential, pkce_required, is_active,
       logo_url, login_theme, login_primary_color,
       created_at, updated_at
FROM oidc_clients
WHERE id = $1
`

func (q *Queries) GetOIDCClientByID(ctx context.Context, id uuid.UUID) (OidcClient, error) {
	row := q.db.QueryRow(ctx, getOIDCClientByID, id)
	var i OidcClient
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Name,
		&i.Description,
		&i.ClientID,
		&i.ClientSecretHash,
		&i.RedirectUris,
		&i.AllowedGrantTypes,
		&i.AllowedScopes,
		&i.RequireConsent,
		&i.IsConfidential,
		&i.PkceRequired,
		&i.IsActive,
		&i.LogoUrl,
		&i.LoginTheme,
		&i.LoginPrimaryColor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmailForOIDC = `-- name: GetUserByEmailForOIDC :one
SELECT id, app_id, email, password_hash, email_verified, is_active,
       name, first_name, last_name, profile_picture, locale,
       two_fa_enabled, two_fa_method, two_fa_secret, two_fa_recovery_codes,
       backup_email, backup_email_verified,
       two_fa_previous_method, two_fa_previous_secret,
       phone_number, phone_verified,
       locked_at, lock_reason, lock_expires_at,
       password_history, password_changed_at,
       created_at, updated_at
FROM users
WHERE app_id = $1 AND email = $2
`

type GetUserByEmailForOIDCParams struct {
	AppID uuid.UUID `json:"app_id"`
	Email string    `json:"email"`
}

func (q *Queries) GetUserByEmailForOIDC(ctx context.Context, arg GetUserByEmailForOIDCParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmailForOIDC, arg.AppID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.IsActive,
		&i.Name,
		&i.FirstName,
		&i.LastName,
		&i.ProfilePicture,
		&i.Locale,
		&i.TwoFaEnabled,
		&i.TwoFaMethod,
		&i.TwoFaSecret,
		&i.TwoFaRecoveryCodes,
		&i.BackupEmail,
		&i.BackupEmailVerified,
		&i.TwoFaPreviousMethod,
		&i.TwoFaPreviousSecret,
		&i.PhoneNumber,
		&i.PhoneVerified,
		&i.LockedAt,
		&i.LockReason,
		&i.LockExpiresAt,
		&i.PasswordHistory,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByIDForOIDC = `-- name: GetUserByIDForOIDC :one
SELECT id, app_id, email, password_hash, email_verified, is_active,
       name, first_name, last_name, profile_picture, locale,
       two_fa_enabled, two_fa_method, two_fa_secret, two_fa_recovery_codes,
       backup_email, backup_email_verified,
       two_fa_previous_method, two_fa_previous_secret,
       phone_number, phone_verified,
       locked_at, lock_reason, lock_expires_at,
       password_history, password_changed_at,
       created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByIDForOIDC(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByIDForOIDC, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.IsActive,
		&i.Name,
		&i.FirstName,
		&i.LastName,
		&i.ProfilePicture,
		&i.Locale,
		&i.TwoFaEnabled,
		&i.TwoFaMethod,
		&i.TwoFaSecret,
		&i.TwoFaRecoveryCodes,
		&i.BackupEmail,
		&i.BackupEmailVerified,
		&i.TwoFaPreviousMethod,
		&i.TwoFaPreviousSecret,
		&i.PhoneNumber,
		&i.PhoneVerified,
		&i.LockedAt,
		&i.LockReason,
		&i.LockExpiresAt,
		&i.PasswordHistory,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOIDCClientsByApp = `-- name: ListOIDCClientsByApp :many
SELECT id, app_id, name, description, client_id, client_secret_hash,
       redirect_uris, allowed_grant_types, allowed_scopes,
       require_consent, is_confidential, pkce_required, is_active,
       logo_url, login_theme, login_primary_color,
       created_at, updated_at
FROM oidc_clients
WHERE app_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListOIDCClientsByApp(ctx context.Context, appID uuid.UUID) ([]OidcClient, error) {
	rows, err := q.db.Query(ctx, listOIDCClientsByApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OidcClient{}
	for rows.Next() {
		var i OidcClient
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.Name,
			&i.Description,
			&i.ClientID,
			&i.ClientSecretHash,
			&i.RedirectUris,
			&i.AllowedGrantTypes,
			&i.AllowedScopes,
			&i.RequireConsent,
			&i.IsConfidential,
			&i.PkceRequired,
			&i.IsActive,
			&i.LogoUrl,
			&i.LoginTheme,
			&i.LoginPrimaryColor,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOIDCAuthCodeUsed = `-- name: MarkOIDCAuthCodeUsed :exec
UPDATE oidc_auth_codes
SET used = TRUE
WHERE id = $1
`

func (q *Queries) MarkOIDCAuthCodeUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOIDCAuthCodeUsed, id)
	return err
}

const saveOIDCRSAPrivateKey = `-- name: SaveOIDCRSAPrivateKey :exec
UPDATE applications
SET oidc_rsa_private_key = $2,
    updated_at = NOW()
WHERE id = $1
`

type SaveOIDCRSAPrivateKeyParams struct {
	ID                uuid.UUID `json:"id"`
	OidcRsaPrivateKey string    `json:"oidc_rsa_private_key"`
}

func (q *Queries) SaveOIDCRSAPrivateKey(ctx context.Context, arg SaveOIDCRSAPrivateKeyParams) error {
	_, err := q.db.Exec(ctx, saveOIDCRSAPrivateKey, arg.ID, arg.OidcRsaPrivateKey)
	return err
}

const updateOIDCClient = `-- name: UpdateOIDCClient :exec
UPDATE oidc_clients
SET app_id              = $2,
    name                = $3,
    description         = $4,
    client_id           = $5,
    client_secret_hash  = $6,
    redirect_uris       = $7,
    allowed_grant_types = $8,
    allowed_scopes      = $9,
    require_consent     = $10,
    is_confidential     = $11,
    pkce_required       = $12,
    is_active           = $13,
    logo_url            = $14,
    login_theme         = $15,
    login_primary_color = $16,
    updated_at          = NOW()
WHERE id = $1
`

type UpdateOIDCClientParams struct {
	ID                uuid.UUID `json:"id"`
	AppID             uuid.UUID `json:"app_id"`
	Name              string    `json:"name"`
	Description       string    `json:"description"`
	ClientID          string    `json:"client_id"`
	ClientSecretHash  string    `json:"client_secret_hash"`
	RedirectUris      string    `json:"redirect_uris"`
	AllowedGrantTypes string    `json:"allowed_grant_types"`
	AllowedScopes     string    `json:"allowed_scopes"`
	RequireConsent    bool      `json:"require_consent"`
	IsConfidential    bool      `json:"is_confidential"`
	PkceRequired      bool      `json:"pkce_required"`
	IsActive          bool      `json:"is_active"`
	LogoUrl           string    `json:"logo_url"`
	LoginTheme        string    `json:"login_theme"`
	LoginPrimaryColor string    `json:"login_primary_color"`
}

func (q *Queries) UpdateOIDCClient(ctx context.Context, arg UpdateOIDCClientParams) error {
	_, err := q.db.Exec(ctx, updateOIDCClient,
		arg.ID,
		arg.AppID,
		arg.Name,
		arg.Description,
		arg.ClientID,
		arg.ClientSecretHash,
		arg.RedirectUris,
		arg.AllowedGrantTypes,
		arg.AllowedScopes,
		arg.RequireConsent,
		arg.IsConfidential,
		arg.PkceRequired,
		arg.IsActive,
		arg.LogoUrl,
		arg.LoginTheme,
		arg.LoginPrimaryColor,
	)
	return err
}
