// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: operator_iam.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertOperatorAccessLog = `-- name: InsertOperatorAccessLog :one
INSERT INTO operator_access_logs (
    kind, key_id, account_id, role_name, method, path, decision, resource, action, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, at, kind, key_id, account_id, role_name, method, path, decision, resource, action, status
`

type InsertOperatorAccessLogParams struct {
	Kind      string      `json:"kind"`
	KeyID     pgtype.UUID `json:"key_id"`
	AccountID pgtype.UUID `json:"account_id"`
	RoleName  string      `json:"role_name"`
	Method    string      `json:"method"`
	Path      string      `json:"path"`
	Decision  string      `json:"decision"`
	Resource  string      `json:"resource"`
	Action    string      `json:"action"`
	Status    int32       `json:"status"`
}

func (q *Queries) InsertOperatorAccessLog(ctx context.Context, arg InsertOperatorAccessLogParams) (OperatorAccessLog, error) {
	row := q.db.QueryRow(ctx, insertOperatorAccessLog,
		arg.Kind,
		arg.KeyID,
		arg.AccountID,
		arg.RoleName,
		arg.Method,
		arg.Path,
		arg.Decision,
		arg.Resource,
		arg.Action,
		arg.Status,
	)
	var i OperatorAccessLog
	err := row.Scan(
		&i.ID,
		&i.At,
		&i.Kind,
		&i.KeyID,
		&i.AccountID,
		&i.RoleName,
		&i.Method,
		&i.Path,
		&i.Decision,
		&i.Resource,
		&i.Action,
		&i.Status,
	)
	return i, err
}

const insertOperatorIAMEvent = `-- name: InsertOperatorIAMEvent :one
INSERT INTO operator_iam_events (
    actor_kind, actor_key_id, actor_account_id,
    target_kind, target_key_id, target_account_id,
    old_role_id, new_role_id, action
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9
)
RETURNING id, at, actor_kind, actor_key_id, actor_account_id, target_kind, target_key_id, target_account_id, old_role_id, new_role_id, action
`

type InsertOperatorIAMEventParams struct {
	ActorKind       string      `json:"actor_kind"`
	ActorKeyID      pgtype.UUID `json:"actor_key_id"`
	ActorAccountID  pgtype.UUID `json:"actor_account_id"`
	TargetKind      string      `json:"target_kind"`
	TargetKeyID     pgtype.UUID `json:"target_key_id"`
	TargetAccountID pgtype.UUID `json:"target_account_id"`
	OldRoleID       pgtype.UUID `json:"old_role_id"`
	NewRoleID       pgtype.UUID `json:"new_role_id"`
	Action          string      `json:"action"`
}

func (q *Queries) InsertOperatorIAMEvent(ctx context.Context, arg InsertOperatorIAMEventParams) (OperatorIamEvent, error) {
	row := q.db.QueryRow(ctx, insertOperatorIAMEvent,
		arg.ActorKind,
		arg.ActorKeyID,
		arg.ActorAccountID,
		arg.TargetKind,
		arg.TargetKeyID,
		arg.TargetAccountID,
		arg.OldRoleID,
		arg.NewRoleID,
		arg.Action,
	)
	var i OperatorIamEvent
	err := row.Scan(
		&i.ID,
		&i.At,
		&i.ActorKind,
		&i.ActorKeyID,
		&i.ActorAccountID,
		&i.TargetKind,
		&i.TargetKeyID,
		&i.TargetAccountID,
		&i.OldRoleID,
		&i.NewRoleID,
		&i.Action,
	)
	return i, err
}

const listOperatorAccessLogs = `-- name: ListOperatorAccessLogs :many
SELECT id, at, kind, key_id, account_id, role_name, method, path, decision, resource, action, status
FROM operator_access_logs
WHERE ($3::text IS NULL OR decision = $3::text)
ORDER BY at DESC
LIMIT $1 OFFSET $2
`

type ListOperatorAccessLogsParams struct {
	Limit    int32   `json:"limit"`
	Offset   int32   `json:"offset"`
	Decision *string `json:"decision"`
}

func (q *Queries) ListOperatorAccessLogs(ctx context.Context, arg ListOperatorAccessLogsParams) ([]OperatorAccessLog, error) {
	rows, err := q.db.Query(ctx, listOperatorAccessLogs, arg.Limit, arg.Offset, arg.Decision)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OperatorAccessLog{}
	for rows.Next() {
		var i OperatorAccessLog
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.Kind,
			&i.KeyID,
			&i.AccountID,
			&i.RoleName,
			&i.Method,
			&i.Path,
			&i.Decision,
			&i.Resource,
			&i.Action,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperatorIAMEvents = `-- name: ListOperatorIAMEvents :many
SELECT id, at, actor_kind, actor_key_id, actor_account_id, target_kind, target_key_id, target_account_id, old_role_id, new_role_id, action
FROM operator_iam_events
WHERE ($3::uuid IS NULL OR target_key_id = $3::uuid)
  AND ($4::uuid IS NULL OR target_account_id = $4::uuid)
ORDER BY at DESC
LIMIT $1 OFFSET $2
`

type ListOperatorIAMEventsParams struct {
	Limit           int32       `json:"limit"`
	Offset          int32       `json:"offset"`
	TargetKeyID     pgtype.UUID `json:"target_key_id"`
	TargetAccountID pgtype.UUID `json:"target_account_id"`
}

func (q *Queries) ListOperatorIAMEvents(ctx context.Context, arg ListOperatorIAMEventsParams) ([]OperatorIamEvent, error) {
	rows, err := q.db.Query(ctx, listOperatorIAMEvents,
		arg.Limit,
		arg.Offset,
		arg.TargetKeyID,
		arg.TargetAccountID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OperatorIamEvent{}
	for rows.Next() {
		var i OperatorIamEvent
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.ActorKind,
			&i.ActorKeyID,
			&i.ActorAccountID,
			&i.TargetKind,
			&i.TargetKeyID,
			&i.TargetAccountID,
			&i.OldRoleID,
			&i.NewRoleID,
			&i.Action,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
