// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: operator.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const getOperatorRoleByID = `-- name: GetOperatorRoleByID :one
SELECT id, name, description, is_system, created_at, updated_at
FROM operator_roles
WHERE id = $1
`

func (q *Queries) GetOperatorRoleByID(ctx context.Context, id uuid.UUID) (OperatorRole, error) {
	row := q.db.QueryRow(ctx, getOperatorRoleByID, id)
	var i OperatorRole
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOperatorRoleByName = `-- name: GetOperatorRoleByName :one

SELECT id, name, description, is_system, created_at, updated_at
FROM operator_roles
WHERE name = $1
`

// ============================================================================
// Operator IAM
// ============================================================================
func (q *Queries) GetOperatorRoleByName(ctx context.Context, name string) (OperatorRole, error) {
	row := q.db.QueryRow(ctx, getOperatorRoleByName, name)
	var i OperatorRole
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOperatorPermissions = `-- name: ListOperatorPermissions :many
SELECT id, resource, action, description, created_at
FROM operator_permissions
ORDER BY resource ASC, action ASC
`

func (q *Queries) ListOperatorPermissions(ctx context.Context) ([]OperatorPermission, error) {
	rows, err := q.db.Query(ctx, listOperatorPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OperatorPermission{}
	for rows.Next() {
		var i OperatorPermission
		if err := rows.Scan(
			&i.ID,
			&i.Resource,
			&i.Action,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperatorPermissionsByRoleID = `-- name: ListOperatorPermissionsByRoleID :many
SELECT p.id, p.resource, p.action, p.description, p.created_at
FROM operator_permissions p
JOIN operator_role_permissions rp ON rp.permission_id = p.id
WHERE rp.role_id = $1
ORDER BY p.resource ASC, p.action ASC
`

func (q *Queries) ListOperatorPermissionsByRoleID(ctx context.Context, roleID uuid.UUID) ([]OperatorPermission, error) {
	rows, err := q.db.Query(ctx, listOperatorPermissionsByRoleID, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OperatorPermission{}
	for rows.Next() {
		var i OperatorPermission
		if err := rows.Scan(
			&i.ID,
			&i.Resource,
			&i.Action,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperatorRoles = `-- name: ListOperatorRoles :many
SELECT id, name, description, is_system, created_at, updated_at
FROM operator_roles
ORDER BY is_system DESC, name ASC
`

func (q *Queries) ListOperatorRoles(ctx context.Context) ([]OperatorRole, error) {
	rows, err := q.db.Query(ctx, listOperatorRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OperatorRole{}
	for rows.Next() {
		var i OperatorRole
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
