// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rbac.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUsersWithRoleInApp = `-- name: CountUsersWithRoleInApp :one
SELECT COUNT(*) FROM user_roles WHERE app_id = $1
`

func (q *Queries) CountUsersWithRoleInApp(ctx context.Context, appID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersWithRoleInApp, appID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPermission = `-- name: CreatePermission :exec
INSERT INTO permissions (id, resource, action, description, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreatePermissionParams struct {
	ID          uuid.UUID `json:"id"`
	Resource    string    `json:"resource"`
	Action      string    `json:"action"`
	Description *string   `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) error {
	_, err := q.db.Exec(ctx, createPermission,
		arg.ID,
		arg.Resource,
		arg.Action,
		arg.Description,
		arg.CreatedAt,
	)
	return err
}

const createRole = `-- name: CreateRole :exec
INSERT INTO roles (id, app_id, name, description, is_system, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateRoleParams struct {
	ID          uuid.UUID `json:"id"`
	AppID       uuid.UUID `json:"app_id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	IsSystem    bool      `json:"is_system"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) error {
	_, err := q.db.Exec(ctx, createRole,
		arg.ID,
		arg.AppID,
		arg.Name,
		arg.Description,
		arg.IsSystem,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createUserRole = `-- name: CreateUserRole :exec
INSERT INTO user_roles (user_id, role_id, app_id, assigned_at, assigned_by)
VALUES ($1, $2, $3, $4, $5)
`

type CreateUserRoleParams struct {
	UserID     uuid.UUID   `json:"user_id"`
	RoleID     uuid.UUID   `json:"role_id"`
	AppID      uuid.UUID   `json:"app_id"`
	AssignedAt time.Time   `json:"assigned_at"`
	AssignedBy pgtype.UUID `json:"assigned_by"`
}

func (q *Queries) CreateUserRole(ctx context.Context, arg CreateUserRoleParams) error {
	_, err := q.db.Exec(ctx, createUserRole,
		arg.UserID,
		arg.RoleID,
		arg.AppID,
		arg.AssignedAt,
		arg.AssignedBy,
	)
	return err
}

const deleteRoleByID = `-- name: DeleteRoleByID :exec
DELETE FROM roles WHERE id = $1
`

func (q *Queries) DeleteRoleByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRoleByID, id)
	return err
}

const deleteRolePermissions = `-- name: DeleteRolePermissions :exec

DELETE FROM role_permissions WHERE role_id = $1
`

// ============================================================================
// Role-Permission operations
// ============================================================================
func (q *Queries) DeleteRolePermissions(ctx context.Context, roleID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRolePermissions, roleID)
	return err
}

const deleteUserRole = `-- name: DeleteUserRole :exec
DELETE FROM user_roles WHERE user_id = $1 AND role_id = $2
`

type DeleteUserRoleParams struct {
	UserID uuid.UUID `json:"user_id"`
	RoleID uuid.UUID `json:"role_id"`
}

func (q *Queries) DeleteUserRole(ctx context.Context, arg DeleteUserRoleParams) error {
	_, err := q.db.Exec(ctx, deleteUserRole, arg.UserID, arg.RoleID)
	return err
}

const getAllPermissions = `-- name: GetAllPermissions :many

SELECT id, resource, action, description, created_at
FROM permissions
ORDER BY resource ASC, action ASC
`

// ============================================================================
// Permission operations
// ============================================================================
func (q *Queries) GetAllPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, getAllPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Resource,
			&i.Action,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPermissionByID = `-- name: GetPermissionByID :one
SELECT id, resource, action, description, created_at
FROM permissions
WHERE id = $1
`

func (q *Queries) GetPermissionByID(ctx context.Context, id uuid.UUID) (Permission, error) {
	row := q.db.QueryRow(ctx, getPermissionByID, id)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Resource,
		&i.Action,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getPermissionsByIDs = `-- name: GetPermissionsByIDs :many
SELECT id, resource, action, description, created_at
FROM permissions
WHERE id = ANY($1::uuid[])
`

func (q *Queries) GetPermissionsByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]Permission, error) {
	rows, err := q.db.Query(ctx, getPermissionsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Resource,
			&i.Action,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPermissionsByRoleID = `-- name: GetPermissionsByRoleID :many
SELECT p.id, p.resource, p.action, p.description, p.created_at
FROM permissions p
JOIN role_permissions rp ON rp.permission_id = p.id
WHERE rp.role_id = $1
ORDER BY p.resource ASC, p.action ASC
`

func (q *Queries) GetPermissionsByRoleID(ctx context.Context, roleID uuid.UUID) ([]Permission, error) {
	rows, err := q.db.Query(ctx, getPermissionsByRoleID, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Resource,
			&i.Action,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, app_id, name, description, is_system, created_at, updated_at
FROM roles
WHERE id = $1
`

func (q *Queries) GetRoleByID(ctx context.Context, id uuid.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, app_id, name, description, is_system, created_at, updated_at
FROM roles
WHERE app_id = $1 AND name = $2
`

type GetRoleByNameParams struct {
	AppID uuid.UUID `json:"app_id"`
	Name  string    `json:"name"`
}

func (q *Queries) GetRoleByName(ctx context.Context, arg GetRoleByNameParams) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByName, arg.AppID, arg.Name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRolesByAppID = `-- name: GetRolesByAppID :many

SELECT id, app_id, name, description, is_system, created_at, updated_at
FROM roles
WHERE app_id = $1
ORDER BY is_system DESC, name ASC
`

// ============================================================================
// Role operations
// ============================================================================
func (q *Queries) GetRolesByAppID(ctx context.Context, appID uuid.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, getRolesByAppID, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRolesForUserInApp = `-- name: GetRolesForUserInApp :many
SELECT r.id, r.app_id, r.name, r.description, r.is_system, r.created_at, r.updated_at
FROM user_roles ur
JOIN roles r ON r.id = ur.role_id
WHERE ur.app_id = $1 AND ur.user_id = $2
`

type GetRolesForUserInAppParams struct {
	AppID  uuid.UUID `json:"app_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetRolesForUserInApp(ctx context.Context, arg GetRolesForUserInAppParams) ([]Role, error) {
	rows, err := q.db.Query(ctx, getRolesForUserInApp, arg.AppID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPermissions = `-- name: GetUserPermissions :many
SELECT DISTINCT p.resource, p.action
FROM user_roles ur
JOIN role_permissions rp ON rp.role_id = ur.role_id
JOIN permissions p ON p.id = rp.permission_id
WHERE ur.app_id = $1 AND ur.user_id = $2
`

type GetUserPermissionsParams struct {
	AppID  uuid.UUID `json:"app_id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetUserPermissionsRow struct {
	Resource string `json:"resource"`
	Action   string `json:"action"`
}

func (q *Queries) GetUserPermissions(ctx context.Context, arg GetUserPermissionsParams) ([]GetUserPermissionsRow, error) {
	rows, err := q.db.Query(ctx, getUserPermissions, arg.AppID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserPermissionsRow{}
	for rows.Next() {
		var i GetUserPermissionsRow
		if err := rows.Scan(&i.Resource, &i.Action); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRoleNames = `-- name: GetUserRoleNames :many

SELECT r.name
FROM user_roles ur
JOIN roles r ON r.id = ur.role_id
WHERE ur.app_id = $1 AND ur.user_id = $2
`

type GetUserRoleNamesParams struct {
	AppID  uuid.UUID `json:"app_id"`
	UserID uuid.UUID `json:"user_id"`
}

// ============================================================================
// User-Role operations
// ============================================================================
func (q *Queries) GetUserRoleNames(ctx context.Context, arg GetUserRoleNamesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserRoleNames, arg.AppID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRolesForUserInApp = `-- name: GetUserRolesForUserInApp :many
SELECT ur.user_id, ur.role_id, ur.app_id, ur.assigned_at, ur.assigned_by
FROM user_roles ur
WHERE ur.app_id = $1 AND ur.user_id = $2
`

type GetUserRolesForUserInAppParams struct {
	AppID  uuid.UUID `json:"app_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetUserRolesForUserInApp(ctx context.Context, arg GetUserRolesForUserInAppParams) ([]UserRole, error) {
	rows, err := q.db.Query(ctx, getUserRolesForUserInApp, arg.AppID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserRole{}
	for rows.Next() {
		var i UserRole
		if err := rows.Scan(
			&i.UserID,
			&i.RoleID,
			&i.AppID,
			&i.AssignedAt,
			&i.AssignedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersWithRoleInApp = `-- name: GetUsersWithRoleInApp :many
SELECT ur.user_id, ur.role_id, ur.app_id, ur.assigned_at,
       u.email AS user_email, u.name AS user_name,
       r.name AS role_name
FROM user_roles ur
JOIN users u ON u.id = ur.user_id
JOIN roles r ON r.id = ur.role_id
WHERE ur.app_id = $1
ORDER BY u.email ASC, r.name ASC
LIMIT $2 OFFSET $3
`

type GetUsersWithRoleInAppParams struct {
	AppID  uuid.UUID `json:"app_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type GetUsersWithRoleInAppRow struct {
	UserID     uuid.UUID `json:"user_id"`
	RoleID     uuid.UUID `json:"role_id"`
	AppID      uuid.UUID `json:"app_id"`
	AssignedAt time.Time `json:"assigned_at"`
	UserEmail  string    `json:"user_email"`
	UserName   string    `json:"user_name"`
	RoleName   string    `json:"role_name"`
}

func (q *Queries) GetUsersWithRoleInApp(ctx context.Context, arg GetUsersWithRoleInAppParams) ([]GetUsersWithRoleInAppRow, error) {
	rows, err := q.db.Query(ctx, getUsersWithRoleInApp, arg.AppID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsersWithRoleInAppRow{}
	for rows.Next() {
		var i GetUsersWithRoleInAppRow
		if err := rows.Scan(
			&i.UserID,
			&i.RoleID,
			&i.AppID,
			&i.AssignedAt,
			&i.UserEmail,
			&i.UserName,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRolePermission = `-- name: InsertRolePermission :exec
INSERT INTO role_permissions (role_id, permission_id) VALUES ($1, $2)
`

type InsertRolePermissionParams struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

func (q *Queries) InsertRolePermission(ctx context.Context, arg InsertRolePermissionParams) error {
	_, err := q.db.Exec(ctx, insertRolePermission, arg.RoleID, arg.PermissionID)
	return err
}

const listAllApps = `-- name: ListAllApps :many

SELECT id, name FROM applications ORDER BY name ASC
`

type ListAllAppsRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

// ============================================================================
// Application operations
// ============================================================================
func (q *Queries) ListAllApps(ctx context.Context) ([]ListAllAppsRow, error) {
	rows, err := q.db.Query(ctx, listAllApps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllAppsRow{}
	for rows.Next() {
		var i ListAllAppsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRole = `-- name: UpdateRole :exec
UPDATE roles SET name = $2, description = $3, updated_at = NOW()
WHERE id = $1
`

type UpdateRoleParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) error {
	_, err := q.db.Exec(ctx, updateRole, arg.ID, arg.Name, arg.Description)
	return err
}
