// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package sqlcgen

import (
	"context"
)

const deleteSetting = `-- name: DeleteSetting :exec
DELETE FROM system_settings
WHERE key = $1
`

func (q *Queries) DeleteSetting(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, deleteSetting, key)
	return err
}

const getAllSettings = `-- name: GetAllSettings :many
SELECT key, value, category, updated_at
FROM system_settings
ORDER BY category ASC, key ASC
`

func (q *Queries) GetAllSettings(ctx context.Context) ([]SystemSetting, error) {
	rows, err := q.db.Query(ctx, getAllSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemSetting{}
	for rows.Next() {
		var i SystemSetting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.Category,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSettingByKey = `-- name: GetSettingByKey :one
SELECT key, value, category, updated_at
FROM system_settings
WHERE key = $1
`

func (q *Queries) GetSettingByKey(ctx context.Context, key string) (SystemSetting, error) {
	row := q.db.QueryRow(ctx, getSettingByKey, key)
	var i SystemSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Category,
		&i.UpdatedAt,
	)
	return i, err
}

const getSettingsByCategory = `-- name: GetSettingsByCategory :many
SELECT key, value, category, updated_at
FROM system_settings
WHERE category = $1
ORDER BY key ASC
`

func (q *Queries) GetSettingsByCategory(ctx context.Context, category string) ([]SystemSetting, error) {
	rows, err := q.db.Query(ctx, getSettingsByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemSetting{}
	for rows.Next() {
		var i SystemSetting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.Category,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO system_settings (key, value, category, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (key) DO UPDATE SET value = $2, updated_at = NOW()
`

type UpsertSettingParams struct {
	Key      string `json:"key"`
	Value    string `json:"value"`
	Category string `json:"category"`
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.Exec(ctx, upsertSetting, arg.Key, arg.Value, arg.Category)
	return err
}
