// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: social.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countSocialAccountsByUserID = `-- name: CountSocialAccountsByUserID :one
SELECT COUNT(*) FROM social_accounts
WHERE user_id = $1
`

func (q *Queries) CountSocialAccountsByUserID(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSocialAccountsByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSocialAccount = `-- name: CreateSocialAccount :exec
INSERT INTO social_accounts (
    id, app_id, user_id, provider, provider_user_id,
    email, name, first_name, last_name, profile_picture,
    username, locale, raw_data, access_token, refresh_token,
    expires_at, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15,
    $16, $17, $18
)
`

type CreateSocialAccountParams struct {
	ID             uuid.UUID          `json:"id"`
	AppID          uuid.UUID          `json:"app_id"`
	UserID         uuid.UUID          `json:"user_id"`
	Provider       string             `json:"provider"`
	ProviderUserID string             `json:"provider_user_id"`
	Email          string             `json:"email"`
	Name           string             `json:"name"`
	FirstName      string             `json:"first_name"`
	LastName       string             `json:"last_name"`
	ProfilePicture string             `json:"profile_picture"`
	Username       string             `json:"username"`
	Locale         string             `json:"locale"`
	RawData        []byte             `json:"raw_data"`
	AccessToken    string             `json:"access_token"`
	RefreshToken   string             `json:"refresh_token"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
}

func (q *Queries) CreateSocialAccount(ctx context.Context, arg CreateSocialAccountParams) error {
	_, err := q.db.Exec(ctx, createSocialAccount,
		arg.ID,
		arg.AppID,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.Email,
		arg.Name,
		arg.FirstName,
		arg.LastName,
		arg.ProfilePicture,
		arg.Username,
		arg.Locale,
		arg.RawData,
		arg.AccessToken,
		arg.RefreshToken,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteSocialAccount = `-- name: DeleteSocialAccount :exec
DELETE FROM social_accounts
WHERE id = $1
`

func (q *Queries) DeleteSocialAccount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSocialAccount, id)
	return err
}

const getOAuthProviderConfig = `-- name: GetOAuthProviderConfig :one
SELECT id, app_id, provider, client_id, client_secret, redirect_url, is_enabled, created_at, updated_at
FROM oauth_provider_configs
WHERE app_id = $1 AND provider = $2
`

type GetOAuthProviderConfigParams struct {
	AppID    uuid.UUID `json:"app_id"`
	Provider string    `json:"provider"`
}

func (q *Queries) GetOAuthProviderConfig(ctx context.Context, arg GetOAuthProviderConfigParams) (OauthProviderConfig, error) {
	row := q.db.QueryRow(ctx, getOAuthProviderConfig, arg.AppID, arg.Provider)
	var i OauthProviderConfig
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Provider,
		&i.ClientID,
		&i.ClientSecret,
		&i.RedirectUrl,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSocialAccountByID = `-- name: GetSocialAccountByID :one
SELECT id, app_id, user_id, provider, provider_user_id,
       email, name, first_name, last_name, profile_picture,
       username, locale, raw_data, access_token, refresh_token,
       expires_at, created_at, updated_at
FROM social_accounts
WHERE id = $1
`

func (q *Queries) GetSocialAccountByID(ctx context.Context, id uuid.UUID) (SocialAccount, error) {
	row := q.db.QueryRow(ctx, getSocialAccountByID, id)
	var i SocialAccount
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Email,
		&i.Name,
		&i.FirstName,
		&i.LastName,
		&i.ProfilePicture,
		&i.Username,
		&i.Locale,
		&i.RawData,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSocialAccountByProviderAndUserID = `-- name: GetSocialAccountByProviderAndUserID :one
SELECT id, app_id, user_id, provider, provider_user_id,
       email, name, first_name, last_name, profile_picture,
       username, locale, raw_data, access_token, refresh_token,
       expires_at, created_at, updated_at
FROM social_accounts
WHERE app_id = $1 AND provider = $2 AND provider_user_id = $3
`

type GetSocialAccountByProviderAndUserIDParams struct {
	AppID          uuid.UUID `json:"app_id"`
	Provider       string    `json:"provider"`
	ProviderUserID string    `json:"provider_user_id"`
}

func (q *Queries) GetSocialAccountByProviderAndUserID(ctx context.Context, arg GetSocialAccountByProviderAndUserIDParams) (SocialAccount, error) {
	row := q.db.QueryRow(ctx, getSocialAccountByProviderAndUserID, arg.AppID, arg.Provider, arg.ProviderUserID)
	var i SocialAccount
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Email,
		&i.Name,
		&i.FirstName,
		&i.LastName,
		&i.ProfilePicture,
		&i.Username,
		&i.Locale,
		&i.RawData,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSocialAccountsByUserID = `-- name: GetSocialAccountsByUserID :many
SELECT id, app_id, user_id, provider, provider_user_id,
       email, name, first_name, last_name, profile_picture,
       username, locale, raw_data, access_token, refresh_token,
       expires_at, created_at, updated_at
FROM social_accounts
WHERE user_id = $1
`

func (q *Queries) GetSocialAccountsByUserID(ctx context.Context, userID uuid.UUID) ([]SocialAccount, error) {
	rows, err := q.db.Query(ctx, getSocialAccountsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SocialAccount{}
	for rows.Next() {
		var i SocialAccount
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.UserID,
			&i.Provider,
			&i.ProviderUserID,
			&i.Email,
			&i.Name,
			&i.FirstName,
			&i.LastName,
			&i.ProfilePicture,
			&i.Username,
			&i.Locale,
			&i.RawData,
			&i.AccessToken,
			&i.RefreshToken,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSocialAccount = `-- name: UpdateSocialAccount :exec
UPDATE social_accounts
SET app_id           = $2,
    user_id          = $3,
    provider         = $4,
    provider_user_id = $5,
    email            = $6,
    name             = $7,
    first_name       = $8,
    last_name        = $9,
    profile_picture  = $10,
    username         = $11,
    locale           = $12,
    raw_data         = $13,
    access_token     = $14,
    refresh_token    = $15,
    expires_at       = $16,
    updated_at       = NOW()
WHERE id = $1
`

type UpdateSocialAccountParams struct {
	ID             uuid.UUID          `json:"id"`
	AppID          uuid.UUID          `json:"app_id"`
	UserID         uuid.UUID          `json:"user_id"`
	Provider       string             `json:"provider"`
	ProviderUserID string             `json:"provider_user_id"`
	Email          string             `json:"email"`
	Name           string             `json:"name"`
	FirstName      string             `json:"first_name"`
	LastName       string             `json:"last_name"`
	ProfilePicture string             `json:"profile_picture"`
	Username       string             `json:"username"`
	Locale         string             `json:"locale"`
	RawData        []byte             `json:"raw_data"`
	AccessToken    string             `json:"access_token"`
	RefreshToken   string             `json:"refresh_token"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpdateSocialAccount(ctx context.Context, arg UpdateSocialAccountParams) error {
	_, err := q.db.Exec(ctx, updateSocialAccount,
		arg.ID,
		arg.AppID,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.Email,
		arg.Name,
		arg.FirstName,
		arg.LastName,
		arg.ProfilePicture,
		arg.Username,
		arg.Locale,
		arg.RawData,
		arg.AccessToken,
		arg.RefreshToken,
		arg.ExpiresAt,
	)
	return err
}

const updateSocialAccountTokens = `-- name: UpdateSocialAccountTokens :exec
UPDATE social_accounts
SET access_token  = $2,
    refresh_token = $3,
    updated_at    = NOW()
WHERE id = $1
`

type UpdateSocialAccountTokensParams struct {
	ID           uuid.UUID `json:"id"`
	AccessToken  string    `json:"access_token"`
	RefreshToken string    `json:"refresh_token"`
}

func (q *Queries) UpdateSocialAccountTokens(ctx context.Context, arg UpdateSocialAccountTokensParams) error {
	_, err := q.db.Exec(ctx, updateSocialAccountTokens, arg.ID, arg.AccessToken, arg.RefreshToken)
	return err
}
