// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trusted_device.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countAllActiveTrustedDevices = `-- name: CountAllActiveTrustedDevices :one
SELECT COUNT(*) FROM trusted_devices
WHERE expires_at > NOW()
`

func (q *Queries) CountAllActiveTrustedDevices(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllActiveTrustedDevices)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTrustedDevicesByUserAndApp = `-- name: CountTrustedDevicesByUserAndApp :one
SELECT COUNT(*) FROM trusted_devices
WHERE user_id = $1 AND app_id = $2 AND expires_at > NOW()
`

type CountTrustedDevicesByUserAndAppParams struct {
	UserID uuid.UUID `json:"user_id"`
	AppID  uuid.UUID `json:"app_id"`
}

func (q *Queries) CountTrustedDevicesByUserAndApp(ctx context.Context, arg CountTrustedDevicesByUserAndAppParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTrustedDevicesByUserAndApp, arg.UserID, arg.AppID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTrustedDevice = `-- name: CreateTrustedDevice :exec
INSERT INTO trusted_devices (id, user_id, app_id, token_hash, name, user_agent, ip_address, last_used_at, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateTrustedDeviceParams struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	AppID      uuid.UUID `json:"app_id"`
	TokenHash  string    `json:"token_hash"`
	Name       *string   `json:"name"`
	UserAgent  *string   `json:"user_agent"`
	IpAddress  *string   `json:"ip_address"`
	LastUsedAt time.Time `json:"last_used_at"`
	ExpiresAt  time.Time `json:"expires_at"`
	CreatedAt  time.Time `json:"created_at"`
}

func (q *Queries) CreateTrustedDevice(ctx context.Context, arg CreateTrustedDeviceParams) error {
	_, err := q.db.Exec(ctx, createTrustedDevice,
		arg.ID,
		arg.UserID,
		arg.AppID,
		arg.TokenHash,
		arg.Name,
		arg.UserAgent,
		arg.IpAddress,
		arg.LastUsedAt,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const deleteAllTrustedDevicesForUser = `-- name: DeleteAllTrustedDevicesForUser :exec
DELETE FROM trusted_devices
WHERE user_id = $1 AND app_id = $2
`

type DeleteAllTrustedDevicesForUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	AppID  uuid.UUID `json:"app_id"`
}

func (q *Queries) DeleteAllTrustedDevicesForUser(ctx context.Context, arg DeleteAllTrustedDevicesForUserParams) error {
	_, err := q.db.Exec(ctx, deleteAllTrustedDevicesForUser, arg.UserID, arg.AppID)
	return err
}

const deleteAllTrustedDevicesForUserAllApps = `-- name: DeleteAllTrustedDevicesForUserAllApps :exec
DELETE FROM trusted_devices
WHERE user_id = $1
`

func (q *Queries) DeleteAllTrustedDevicesForUserAllApps(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllTrustedDevicesForUserAllApps, userID)
	return err
}

const deleteExpiredTrustedDevices = `-- name: DeleteExpiredTrustedDevices :execrows
DELETE FROM trusted_devices
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredTrustedDevices(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredTrustedDevices)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTrustedDeviceByID = `-- name: DeleteTrustedDeviceByID :exec
DELETE FROM trusted_devices
WHERE id = $1
`

func (q *Queries) DeleteTrustedDeviceByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTrustedDeviceByID, id)
	return err
}

const deleteTrustedDevicesByUserAppAndUserAgent = `-- name: DeleteTrustedDevicesByUserAppAndUserAgent :exec
DELETE FROM trusted_devices
WHERE user_id = $1 AND app_id = $2 AND user_agent = $3
`

type DeleteTrustedDevicesByUserAppAndUserAgentParams struct {
	UserID    uuid.UUID `json:"user_id"`
	AppID     uuid.UUID `json:"app_id"`
	UserAgent *string   `json:"user_agent"`
}

func (q *Queries) DeleteTrustedDevicesByUserAppAndUserAgent(ctx context.Context, arg DeleteTrustedDevicesByUserAppAndUserAgentParams) error {
	_, err := q.db.Exec(ctx, deleteTrustedDevicesByUserAppAndUserAgent, arg.UserID, arg.AppID, arg.UserAgent)
	return err
}

const findAllTrustedDevicesForUser = `-- name: FindAllTrustedDevicesForUser :many
SELECT id, user_id, app_id, token_hash, name, user_agent, ip_address, last_used_at, expires_at, created_at
FROM trusted_devices
WHERE user_id = $1 AND expires_at > NOW()
ORDER BY last_used_at DESC
`

func (q *Queries) FindAllTrustedDevicesForUser(ctx context.Context, userID uuid.UUID) ([]TrustedDevice, error) {
	rows, err := q.db.Query(ctx, findAllTrustedDevicesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrustedDevice{}
	for rows.Next() {
		var i TrustedDevice
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AppID,
			&i.TokenHash,
			&i.Name,
			&i.UserAgent,
			&i.IpAddress,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findTrustedDeviceByID = `-- name: FindTrustedDeviceByID :one
SELECT id, user_id, app_id, token_hash, name, user_agent, ip_address, last_used_at, expires_at, created_at
FROM trusted_devices
WHERE id = $1
`

func (q *Queries) FindTrustedDeviceByID(ctx context.Context, id uuid.UUID) (TrustedDevice, error) {
	row := q.db.QueryRow(ctx, findTrustedDeviceByID, id)
	var i TrustedDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AppID,
		&i.TokenHash,
		&i.Name,
		&i.UserAgent,
		&i.IpAddress,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const findTrustedDeviceByTokenHash = `-- name: FindTrustedDeviceByTokenHash :one
SELECT id, user_id, app_id, token_hash, name, user_agent, ip_address, last_used_at, expires_at, created_at
FROM trusted_devices
WHERE token_hash = $1
`

func (q *Queries) FindTrustedDeviceByTokenHash(ctx context.Context, tokenHash string) (TrustedDevice, error) {
	row := q.db.QueryRow(ctx, findTrustedDeviceByTokenHash, tokenHash)
	var i TrustedDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AppID,
		&i.TokenHash,
		&i.Name,
		&i.UserAgent,
		&i.IpAddress,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const findTrustedDevicesByUserAndApp = `-- name: FindTrustedDevicesByUserAndApp :many
SELECT id, user_id, app_id, token_hash, name, user_agent, ip_address, last_used_at, expires_at, created_at
FROM trusted_devices
WHERE user_id = $1 AND app_id = $2 AND expires_at > NOW()
ORDER BY last_used_at DESC
`

type FindTrustedDevicesByUserAndAppParams struct {
	UserID uuid.UUID `json:"user_id"`
	AppID  uuid.UUID `json:"app_id"`
}

func (q *Queries) FindTrustedDevicesByUserAndApp(ctx context.Context, arg FindTrustedDevicesByUserAndAppParams) ([]TrustedDevice, error) {
	rows, err := q.db.Query(ctx, findTrustedDevicesByUserAndApp, arg.UserID, arg.AppID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrustedDevice{}
	for rows.Next() {
		var i TrustedDevice
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AppID,
			&i.TokenHash,
			&i.Name,
			&i.UserAgent,
			&i.IpAddress,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchTrustedDeviceLastUsed = `-- name: TouchTrustedDeviceLastUsed :exec
UPDATE trusted_devices
SET last_used_at = NOW()
WHERE id = $1
`

func (q *Queries) TouchTrustedDeviceLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchTrustedDeviceLastUsed, id)
	return err
}
