// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlcgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearBackupEmail = `-- name: ClearBackupEmail :exec
UPDATE users
SET backup_email          = '',
    backup_email_verified = FALSE,
    updated_at            = NOW()
WHERE id = $1
`

func (q *Queries) ClearBackupEmail(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearBackupEmail, id)
	return err
}

const clearLockout = `-- name: ClearLockout :exec
UPDATE users
SET locked_at       = NULL,
    lock_reason     = '',
    lock_expires_at = NULL,
    updated_at      = NOW()
WHERE id = $1
`

func (q *Queries) ClearLockout(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearLockout, id)
	return err
}

const clearPhone = `-- name: ClearPhone :exec
UPDATE users
SET phone_number   = '',
    phone_verified = FALSE,
    updated_at     = NOW()
WHERE id = $1
`

func (q *Queries) ClearPhone(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearPhone, id)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id, app_id, email, password_hash, email_verified, is_active,
    name, first_name, last_name, profile_picture, locale,
    two_fa_enabled, two_fa_method, two_fa_secret, two_fa_recovery_codes,
    backup_email, backup_email_verified,
    two_fa_previous_method, two_fa_previous_secret,
    phone_number, phone_verified,
    locked_at, lock_reason, lock_expires_at,
    password_history, password_changed_at,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13, $14, $15,
    $16, $17,
    $18, $19,
    $20, $21,
    $22, $23, $24,
    $25, $26,
    $27, $28
)
RETURNING id, app_id, email, password_hash, email_verified, is_active, name, first_name, last_name, profile_picture, locale, two_fa_enabled, two_fa_method, two_fa_secret, two_fa_recovery_codes, backup_email, backup_email_verified, two_fa_previous_method, two_fa_previous_secret, phone_number, phone_verified, locked_at, lock_reason, lock_expires_at, password_history, password_changed_at, created_at, updated_at
`

type CreateUserParams struct {
	ID                  uuid.UUID          `json:"id"`
	AppID               uuid.UUID          `json:"app_id"`
	Email               string             `json:"email"`
	PasswordHash        string             `json:"password_hash"`
	EmailVerified       bool               `json:"email_verified"`
	IsActive            bool               `json:"is_active"`
	Name                string             `json:"name"`
	FirstName           string             `json:"first_name"`
	LastName            string             `json:"last_name"`
	ProfilePicture      string             `json:"profile_picture"`
	Locale              string             `json:"locale"`
	TwoFaEnabled        bool               `json:"two_fa_enabled"`
	TwoFaMethod         string             `json:"two_fa_method"`
	TwoFaSecret         string             `json:"two_fa_secret"`
	TwoFaRecoveryCodes  json.RawMessage    `json:"two_fa_recovery_codes"`
	BackupEmail         string             `json:"backup_email"`
	BackupEmailVerified bool               `json:"backup_email_verified"`
	TwoFaPreviousMethod string             `json:"two_fa_previous_method"`
	TwoFaPreviousSecret string             `json:"two_fa_previous_secret"`
	PhoneNumber         string             `json:"phone_number"`
	PhoneVerified       bool               `json:"phone_verified"`
	LockedAt            pgtype.Timestamptz `json:"locked_at"`
	LockReason          string             `json:"lock_reason"`
	LockExpiresAt       pgtype.Timestamptz `json:"lock_expires_at"`
	PasswordHistory     []byte             `json:"password_history"`
	PasswordChangedAt   pgtype.Timestamptz `json:"password_changed_at"`
	CreatedAt           time.Time          `json:"created_at"`
	UpdatedAt           time.Time          `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.AppID,
		arg.Email,
		arg.PasswordHash,
		arg.EmailVerified,
		arg.IsActive,
		arg.Name,
		arg.FirstName,
		arg.LastName,
		arg.ProfilePicture,
		arg.Locale,
		arg.TwoFaEnabled,
		arg.TwoFaMethod,
		arg.TwoFaSecret,
		arg.TwoFaRecoveryCodes,
		arg.BackupEmail,
		arg.BackupEmailVerified,
		arg.TwoFaPreviousMethod,
		arg.TwoFaPreviousSecret,
		arg.PhoneNumber,
		arg.PhoneVerified,
		arg.LockedAt,
		arg.LockReason,
		arg.LockExpiresAt,
		arg.PasswordHistory,
		arg.PasswordChangedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.IsActive,
		&i.Name,
		&i.FirstName,
		&i.LastName,
		&i.ProfilePicture,
		&i.Locale,
		&i.TwoFaEnabled,
		&i.TwoFaMethod,
		&i.TwoFaSecret,
		&i.TwoFaRecoveryCodes,
		&i.BackupEmail,
		&i.BackupEmailVerified,
		&i.TwoFaPreviousMethod,
		&i.TwoFaPreviousSecret,
		&i.PhoneNumber,
		&i.PhoneVerified,
		&i.LockedAt,
		&i.LockReason,
		&i.LockExpiresAt,
		&i.PasswordHistory,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserByID = `-- name: DeleteUserByID :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUserByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserByID, id)
	return err
}

const disable2FA = `-- name: Disable2FA :exec
UPDATE users
SET two_fa_enabled        = FALSE,
    two_fa_secret         = '',
    two_fa_recovery_codes = NULL,
    two_fa_method         = '',
    updated_at            = NOW()
WHERE id = $1
`

func (q *Queries) Disable2FA(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, disable2FA, id)
	return err
}

const enable2FAWithMethod = `-- name: Enable2FAWithMethod :exec
UPDATE users
SET two_fa_enabled        = TRUE,
    two_fa_secret         = $2,
    two_fa_recovery_codes = $3,
    two_fa_method         = $4,
    updated_at            = NOW()
WHERE id = $1
`

type Enable2FAWithMethodParams struct {
	ID                 uuid.UUID       `json:"id"`
	TwoFaSecret        string          `json:"two_fa_secret"`
	TwoFaRecoveryCodes json.RawMessage `json:"two_fa_recovery_codes"`
	TwoFaMethod        string          `json:"two_fa_method"`
}

func (q *Queries) Enable2FAWithMethod(ctx context.Context, arg Enable2FAWithMethodParams) error {
	_, err := q.db.Exec(ctx, enable2FAWithMethod,
		arg.ID,
		arg.TwoFaSecret,
		arg.TwoFaRecoveryCodes,
		arg.TwoFaMethod,
	)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, app_id, email, password_hash, email_verified, is_active, name, first_name, last_name, profile_picture, locale, two_fa_enabled, two_fa_method, two_fa_secret, two_fa_recovery_codes, backup_email, backup_email_verified, two_fa_previous_method, two_fa_previous_secret, phone_number, phone_verified, locked_at, lock_reason, lock_expires_at, password_history, password_changed_at, created_at, updated_at FROM users
WHERE app_id = $1 AND email = $2
`

type GetUserByEmailParams struct {
	AppID uuid.UUID `json:"app_id"`
	Email string    `json:"email"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.AppID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.IsActive,
		&i.Name,
		&i.FirstName,
		&i.LastName,
		&i.ProfilePicture,
		&i.Locale,
		&i.TwoFaEnabled,
		&i.TwoFaMethod,
		&i.TwoFaSecret,
		&i.TwoFaRecoveryCodes,
		&i.BackupEmail,
		&i.BackupEmailVerified,
		&i.TwoFaPreviousMethod,
		&i.TwoFaPreviousSecret,
		&i.PhoneNumber,
		&i.PhoneVerified,
		&i.LockedAt,
		&i.LockReason,
		&i.LockExpiresAt,
		&i.PasswordHistory,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, app_id, email, password_hash, email_verified, is_active, name, first_name, last_name, profile_picture, locale, two_fa_enabled, two_fa_method, two_fa_secret, two_fa_recovery_codes, backup_email, backup_email_verified, two_fa_previous_method, two_fa_previous_secret, phone_number, phone_verified, locked_at, lock_reason, lock_expires_at, password_history, password_changed_at, created_at, updated_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.IsActive,
		&i.Name,
		&i.FirstName,
		&i.LastName,
		&i.ProfilePicture,
		&i.Locale,
		&i.TwoFaEnabled,
		&i.TwoFaMethod,
		&i.TwoFaSecret,
		&i.TwoFaRecoveryCodes,
		&i.BackupEmail,
		&i.BackupEmailVerified,
		&i.TwoFaPreviousMethod,
		&i.TwoFaPreviousSecret,
		&i.PhoneNumber,
		&i.PhoneVerified,
		&i.LockedAt,
		&i.LockReason,
		&i.LockExpiresAt,
		&i.PasswordHistory,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserTwoFAPreviousFields = `-- name: GetUserTwoFAPreviousFields :one
SELECT two_fa_previous_method, two_fa_previous_secret
FROM users
WHERE id = $1
`

type GetUserTwoFAPreviousFieldsRow struct {
	TwoFaPreviousMethod string `json:"two_fa_previous_method"`
	TwoFaPreviousSecret string `json:"two_fa_previous_secret"`
}

func (q *Queries) GetUserTwoFAPreviousFields(ctx context.Context, id uuid.UUID) (GetUserTwoFAPreviousFieldsRow, error) {
	row := q.db.QueryRow(ctx, getUserTwoFAPreviousFields, id)
	var i GetUserTwoFAPreviousFieldsRow
	err := row.Scan(&i.TwoFaPreviousMethod, &i.TwoFaPreviousSecret)
	return i, err
}

const restorePreviousTwoFAMethod = `-- name: RestorePreviousTwoFAMethod :exec
UPDATE users
SET two_fa_method          = $2,
    two_fa_secret          = $3,
    two_fa_enabled         = $4,
    two_fa_previous_method = '',
    two_fa_previous_secret = '',
    updated_at             = NOW()
WHERE id = $1
`

type RestorePreviousTwoFAMethodParams struct {
	ID           uuid.UUID `json:"id"`
	TwoFaMethod  string    `json:"two_fa_method"`
	TwoFaSecret  string    `json:"two_fa_secret"`
	TwoFaEnabled bool      `json:"two_fa_enabled"`
}

func (q *Queries) RestorePreviousTwoFAMethod(ctx context.Context, arg RestorePreviousTwoFAMethodParams) error {
	_, err := q.db.Exec(ctx, restorePreviousTwoFAMethod,
		arg.ID,
		arg.TwoFaMethod,
		arg.TwoFaSecret,
		arg.TwoFaEnabled,
	)
	return err
}

const saveAndSwitchToBackupEmail2FA = `-- name: SaveAndSwitchToBackupEmail2FA :exec
UPDATE users
SET two_fa_previous_method = $2,
    two_fa_previous_secret = $3,
    two_fa_enabled         = TRUE,
    two_fa_method          = 'backup_email',
    two_fa_secret          = '',
    two_fa_recovery_codes  = $4,
    updated_at             = NOW()
WHERE id = $1
`

type SaveAndSwitchToBackupEmail2FAParams struct {
	ID                  uuid.UUID       `json:"id"`
	TwoFaPreviousMethod string          `json:"two_fa_previous_method"`
	TwoFaPreviousSecret string          `json:"two_fa_previous_secret"`
	TwoFaRecoveryCodes  json.RawMessage `json:"two_fa_recovery_codes"`
}

func (q *Queries) SaveAndSwitchToBackupEmail2FA(ctx context.Context, arg SaveAndSwitchToBackupEmail2FAParams) error {
	_, err := q.db.Exec(ctx, saveAndSwitchToBackupEmail2FA,
		arg.ID,
		arg.TwoFaPreviousMethod,
		arg.TwoFaPreviousSecret,
		arg.TwoFaRecoveryCodes,
	)
	return err
}

const setBackupEmail = `-- name: SetBackupEmail :exec
UPDATE users
SET backup_email          = $2,
    backup_email_verified = FALSE,
    updated_at            = NOW()
WHERE id = $1
`

type SetBackupEmailParams struct {
	ID          uuid.UUID `json:"id"`
	BackupEmail string    `json:"backup_email"`
}

func (q *Queries) SetBackupEmail(ctx context.Context, arg SetBackupEmailParams) error {
	_, err := q.db.Exec(ctx, setBackupEmail, arg.ID, arg.BackupEmail)
	return err
}

const setPhoneNumber = `-- name: SetPhoneNumber :exec
UPDATE users
SET phone_number   = $2,
    phone_verified = FALSE,
    updated_at     = NOW()
WHERE id = $1
`

type SetPhoneNumberParams struct {
	ID          uuid.UUID `json:"id"`
	PhoneNumber string    `json:"phone_number"`
}

func (q *Queries) SetPhoneNumber(ctx context.Context, arg SetPhoneNumberParams) error {
	_, err := q.db.Exec(ctx, setPhoneNumber, arg.ID, arg.PhoneNumber)
	return err
}

const updateRecoveryCodes = `-- name: UpdateRecoveryCodes :exec
UPDATE users
SET two_fa_recovery_codes = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateRecoveryCodesParams struct {
	ID                 uuid.UUID       `json:"id"`
	TwoFaRecoveryCodes json.RawMessage `json:"two_fa_recovery_codes"`
}

func (q *Queries) UpdateRecoveryCodes(ctx context.Context, arg UpdateRecoveryCodesParams) error {
	_, err := q.db.Exec(ctx, updateRecoveryCodes, arg.ID, arg.TwoFaRecoveryCodes)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET app_id               = $2,
    email                = $3,
    password_hash        = $4,
    email_verified       = $5,
    is_active            = $6,
    name                 = $7,
    first_name           = $8,
    last_name            = $9,
    profile_picture      = $10,
    locale               = $11,
    two_fa_enabled       = $12,
    two_fa_method        = $13,
    two_fa_secret        = $14,
    two_fa_recovery_codes = $15,
    backup_email         = $16,
    backup_email_verified = $17,
    two_fa_previous_method = $18,
    two_fa_previous_secret = $19,
    phone_number         = $20,
    phone_verified       = $21,
    locked_at            = $22,
    lock_reason          = $23,
    lock_expires_at      = $24,
    password_history     = $25,
    password_changed_at  = $26,
    updated_at           = NOW()
WHERE id = $1
`

type UpdateUserParams struct {
	ID                  uuid.UUID          `json:"id"`
	AppID               uuid.UUID          `json:"app_id"`
	Email               string             `json:"email"`
	PasswordHash        string             `json:"password_hash"`
	EmailVerified       bool               `json:"email_verified"`
	IsActive            bool               `json:"is_active"`
	Name                string             `json:"name"`
	FirstName           string             `json:"first_name"`
	LastName            string             `json:"last_name"`
	ProfilePicture      string             `json:"profile_picture"`
	Locale              string             `json:"locale"`
	TwoFaEnabled        bool               `json:"two_fa_enabled"`
	TwoFaMethod         string             `json:"two_fa_method"`
	TwoFaSecret         string             `json:"two_fa_secret"`
	TwoFaRecoveryCodes  json.RawMessage    `json:"two_fa_recovery_codes"`
	BackupEmail         string             `json:"backup_email"`
	BackupEmailVerified bool               `json:"backup_email_verified"`
	TwoFaPreviousMethod string             `json:"two_fa_previous_method"`
	TwoFaPreviousSecret string             `json:"two_fa_previous_secret"`
	PhoneNumber         string             `json:"phone_number"`
	PhoneVerified       bool               `json:"phone_verified"`
	LockedAt            pgtype.Timestamptz `json:"locked_at"`
	LockReason          string             `json:"lock_reason"`
	LockExpiresAt       pgtype.Timestamptz `json:"lock_expires_at"`
	PasswordHistory     []byte             `json:"password_history"`
	PasswordChangedAt   pgtype.Timestamptz `json:"password_changed_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.AppID,
		arg.Email,
		arg.PasswordHash,
		arg.EmailVerified,
		arg.IsActive,
		arg.Name,
		arg.FirstName,
		arg.LastName,
		arg.ProfilePicture,
		arg.Locale,
		arg.TwoFaEnabled,
		arg.TwoFaMethod,
		arg.TwoFaSecret,
		arg.TwoFaRecoveryCodes,
		arg.BackupEmail,
		arg.BackupEmailVerified,
		arg.TwoFaPreviousMethod,
		arg.TwoFaPreviousSecret,
		arg.PhoneNumber,
		arg.PhoneVerified,
		arg.LockedAt,
		arg.LockReason,
		arg.LockExpiresAt,
		arg.PasswordHistory,
		arg.PasswordChangedAt,
	)
	return err
}

const updateUserEmail = `-- name: UpdateUserEmail :exec
UPDATE users
SET email          = $2,
    email_verified = FALSE,
    updated_at     = NOW()
WHERE id = $1
`

type UpdateUserEmailParams struct {
	ID    uuid.UUID `json:"id"`
	Email string    `json:"email"`
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error {
	_, err := q.db.Exec(ctx, updateUserEmail, arg.ID, arg.Email)
	return err
}

const updateUserEmailVerified = `-- name: UpdateUserEmailVerified :exec
UPDATE users
SET email_verified = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUserEmailVerifiedParams struct {
	ID            uuid.UUID `json:"id"`
	EmailVerified bool      `json:"email_verified"`
}

func (q *Queries) UpdateUserEmailVerified(ctx context.Context, arg UpdateUserEmailVerifiedParams) error {
	_, err := q.db.Exec(ctx, updateUserEmailVerified, arg.ID, arg.EmailVerified)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserPasswordWithHistory = `-- name: UpdateUserPasswordWithHistory :exec
UPDATE users
SET password_hash       = $2,
    password_history    = $3,
    password_changed_at = $4,
    updated_at          = NOW()
WHERE id = $1
`

type UpdateUserPasswordWithHistoryParams struct {
	ID                uuid.UUID          `json:"id"`
	PasswordHash      string             `json:"password_hash"`
	PasswordHistory   []byte             `json:"password_history"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
}

func (q *Queries) UpdateUserPasswordWithHistory(ctx context.Context, arg UpdateUserPasswordWithHistoryParams) error {
	_, err := q.db.Exec(ctx, updateUserPasswordWithHistory,
		arg.ID,
		arg.PasswordHash,
		arg.PasswordHistory,
		arg.PasswordChangedAt,
	)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE users
SET name            = $2,
    first_name      = $3,
    last_name       = $4,
    profile_picture = $5,
    locale          = $6,
    updated_at      = NOW()
WHERE id = $1
`

type UpdateUserProfileParams struct {
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	FirstName      string    `json:"first_name"`
	LastName       string    `json:"last_name"`
	ProfilePicture string    `json:"profile_picture"`
	Locale         string    `json:"locale"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.Exec(ctx, updateUserProfile,
		arg.ID,
		arg.Name,
		arg.FirstName,
		arg.LastName,
		arg.ProfilePicture,
		arg.Locale,
	)
	return err
}

const verifyBackupEmail = `-- name: VerifyBackupEmail :exec
UPDATE users
SET backup_email_verified = TRUE, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) VerifyBackupEmail(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, verifyBackupEmail, id)
	return err
}

const verifyPhoneNumber = `-- name: VerifyPhoneNumber :exec
UPDATE users
SET phone_verified = TRUE, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) VerifyPhoneNumber(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, verifyPhoneNumber, id)
	return err
}
