// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webauthn.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countWebAuthnCredentialsByUserAndApp = `-- name: CountWebAuthnCredentialsByUserAndApp :one
SELECT COUNT(*) FROM webauthn_credentials
WHERE user_id = $1 AND app_id = $2
`

type CountWebAuthnCredentialsByUserAndAppParams struct {
	UserID pgtype.UUID `json:"user_id"`
	AppID  pgtype.UUID `json:"app_id"`
}

func (q *Queries) CountWebAuthnCredentialsByUserAndApp(ctx context.Context, arg CountWebAuthnCredentialsByUserAndAppParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWebAuthnCredentialsByUserAndApp, arg.UserID, arg.AppID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWebAuthnCredential = `-- name: CreateWebAuthnCredential :exec
INSERT INTO webauthn_credentials (
    id, user_id, app_id, admin_id, credential_id, public_key,
    attestation_type, aaguid, sign_count, name, transports,
    backup_eligible, backup_state, last_used_at, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13, $14, $15
)
`

type CreateWebAuthnCredentialParams struct {
	ID              uuid.UUID          `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	AppID           pgtype.UUID        `json:"app_id"`
	AdminID         pgtype.UUID        `json:"admin_id"`
	CredentialID    []byte             `json:"credential_id"`
	PublicKey       []byte             `json:"public_key"`
	AttestationType *string            `json:"attestation_type"`
	Aaguid          []byte             `json:"aaguid"`
	SignCount       int32              `json:"sign_count"`
	Name            *string            `json:"name"`
	Transports      *string            `json:"transports"`
	BackupEligible  bool               `json:"backup_eligible"`
	BackupState     bool               `json:"backup_state"`
	LastUsedAt      pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt       time.Time          `json:"created_at"`
}

func (q *Queries) CreateWebAuthnCredential(ctx context.Context, arg CreateWebAuthnCredentialParams) error {
	_, err := q.db.Exec(ctx, createWebAuthnCredential,
		arg.ID,
		arg.UserID,
		arg.AppID,
		arg.AdminID,
		arg.CredentialID,
		arg.PublicKey,
		arg.AttestationType,
		arg.Aaguid,
		arg.SignCount,
		arg.Name,
		arg.Transports,
		arg.BackupEligible,
		arg.BackupState,
		arg.LastUsedAt,
		arg.CreatedAt,
	)
	return err
}

const deleteWebAuthnAdminCredential = `-- name: DeleteWebAuthnAdminCredential :exec
DELETE FROM webauthn_credentials
WHERE id = $1 AND admin_id = $2
`

type DeleteWebAuthnAdminCredentialParams struct {
	ID      uuid.UUID   `json:"id"`
	AdminID pgtype.UUID `json:"admin_id"`
}

func (q *Queries) DeleteWebAuthnAdminCredential(ctx context.Context, arg DeleteWebAuthnAdminCredentialParams) error {
	_, err := q.db.Exec(ctx, deleteWebAuthnAdminCredential, arg.ID, arg.AdminID)
	return err
}

const deleteWebAuthnCredential = `-- name: DeleteWebAuthnCredential :exec
DELETE FROM webauthn_credentials
WHERE id = $1 AND user_id = $2
`

type DeleteWebAuthnCredentialParams struct {
	ID     uuid.UUID   `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteWebAuthnCredential(ctx context.Context, arg DeleteWebAuthnCredentialParams) error {
	_, err := q.db.Exec(ctx, deleteWebAuthnCredential, arg.ID, arg.UserID)
	return err
}

const getWebAuthnCredentialByAdminAndCredentialID = `-- name: GetWebAuthnCredentialByAdminAndCredentialID :one
SELECT id, user_id, app_id, admin_id, credential_id, public_key,
       attestation_type, aaguid, sign_count, name, transports,
       backup_eligible, backup_state, last_used_at, created_at
FROM webauthn_credentials
WHERE admin_id = $1 AND credential_id = $2
`

type GetWebAuthnCredentialByAdminAndCredentialIDParams struct {
	AdminID      pgtype.UUID `json:"admin_id"`
	CredentialID []byte      `json:"credential_id"`
}

func (q *Queries) GetWebAuthnCredentialByAdminAndCredentialID(ctx context.Context, arg GetWebAuthnCredentialByAdminAndCredentialIDParams) (WebauthnCredential, error) {
	row := q.db.QueryRow(ctx, getWebAuthnCredentialByAdminAndCredentialID, arg.AdminID, arg.CredentialID)
	var i WebauthnCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AppID,
		&i.AdminID,
		&i.CredentialID,
		&i.PublicKey,
		&i.AttestationType,
		&i.Aaguid,
		&i.SignCount,
		&i.Name,
		&i.Transports,
		&i.BackupEligible,
		&i.BackupState,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWebAuthnCredentialByAppAndCredentialID = `-- name: GetWebAuthnCredentialByAppAndCredentialID :one
SELECT id, user_id, app_id, admin_id, credential_id, public_key,
       attestation_type, aaguid, sign_count, name, transports,
       backup_eligible, backup_state, last_used_at, created_at
FROM webauthn_credentials
WHERE app_id = $1 AND credential_id = $2
`

type GetWebAuthnCredentialByAppAndCredentialIDParams struct {
	AppID        pgtype.UUID `json:"app_id"`
	CredentialID []byte      `json:"credential_id"`
}

func (q *Queries) GetWebAuthnCredentialByAppAndCredentialID(ctx context.Context, arg GetWebAuthnCredentialByAppAndCredentialIDParams) (WebauthnCredential, error) {
	row := q.db.QueryRow(ctx, getWebAuthnCredentialByAppAndCredentialID, arg.AppID, arg.CredentialID)
	var i WebauthnCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AppID,
		&i.AdminID,
		&i.CredentialID,
		&i.PublicKey,
		&i.AttestationType,
		&i.Aaguid,
		&i.SignCount,
		&i.Name,
		&i.Transports,
		&i.BackupEligible,
		&i.BackupState,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWebAuthnCredentialByCredentialID = `-- name: GetWebAuthnCredentialByCredentialID :one
SELECT id, user_id, app_id, admin_id, credential_id, public_key,
       attestation_type, aaguid, sign_count, name, transports,
       backup_eligible, backup_state, last_used_at, created_at
FROM webauthn_credentials
WHERE credential_id = $1
`

func (q *Queries) GetWebAuthnCredentialByCredentialID(ctx context.Context, credentialID []byte) (WebauthnCredential, error) {
	row := q.db.QueryRow(ctx, getWebAuthnCredentialByCredentialID, credentialID)
	var i WebauthnCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AppID,
		&i.AdminID,
		&i.CredentialID,
		&i.PublicKey,
		&i.AttestationType,
		&i.Aaguid,
		&i.SignCount,
		&i.Name,
		&i.Transports,
		&i.BackupEligible,
		&i.BackupState,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWebAuthnCredentialByID = `-- name: GetWebAuthnCredentialByID :one
SELECT id, user_id, app_id, admin_id, credential_id, public_key,
       attestation_type, aaguid, sign_count, name, transports,
       backup_eligible, backup_state, last_used_at, created_at
FROM webauthn_credentials
WHERE id = $1
`

func (q *Queries) GetWebAuthnCredentialByID(ctx context.Context, id uuid.UUID) (WebauthnCredential, error) {
	row := q.db.QueryRow(ctx, getWebAuthnCredentialByID, id)
	var i WebauthnCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AppID,
		&i.AdminID,
		&i.CredentialID,
		&i.PublicKey,
		&i.AttestationType,
		&i.Aaguid,
		&i.SignCount,
		&i.Name,
		&i.Transports,
		&i.BackupEligible,
		&i.BackupState,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWebAuthnCredentialsByAdminID = `-- name: GetWebAuthnCredentialsByAdminID :many
SELECT id, user_id, app_id, admin_id, credential_id, public_key,
       attestation_type, aaguid, sign_count, name, transports,
       backup_eligible, backup_state, last_used_at, created_at
FROM webauthn_credentials
WHERE admin_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetWebAuthnCredentialsByAdminID(ctx context.Context, adminID pgtype.UUID) ([]WebauthnCredential, error) {
	rows, err := q.db.Query(ctx, getWebAuthnCredentialsByAdminID, adminID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebauthnCredential{}
	for rows.Next() {
		var i WebauthnCredential
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AppID,
			&i.AdminID,
			&i.CredentialID,
			&i.PublicKey,
			&i.AttestationType,
			&i.Aaguid,
			&i.SignCount,
			&i.Name,
			&i.Transports,
			&i.BackupEligible,
			&i.BackupState,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWebAuthnCredentialsByUserAndApp = `-- name: GetWebAuthnCredentialsByUserAndApp :many
SELECT id, user_id, app_id, admin_id, credential_id, public_key,
       attestation_type, aaguid, sign_count, name, transports,
       backup_eligible, backup_state, last_used_at, created_at
FROM webauthn_credentials
WHERE user_id = $1 AND app_id = $2
ORDER BY created_at ASC
`

type GetWebAuthnCredentialsByUserAndAppParams struct {
	UserID pgtype.UUID `json:"user_id"`
	AppID  pgtype.UUID `json:"app_id"`
}

func (q *Queries) GetWebAuthnCredentialsByUserAndApp(ctx context.Context, arg GetWebAuthnCredentialsByUserAndAppParams) ([]WebauthnCredential, error) {
	rows, err := q.db.Query(ctx, getWebAuthnCredentialsByUserAndApp, arg.UserID, arg.AppID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebauthnCredential{}
	for rows.Next() {
		var i WebauthnCredential
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AppID,
			&i.AdminID,
			&i.CredentialID,
			&i.PublicKey,
			&i.AttestationType,
			&i.Aaguid,
			&i.SignCount,
			&i.Name,
			&i.Transports,
			&i.BackupEligible,
			&i.BackupState,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWebAuthnCredentialsByUserID = `-- name: GetWebAuthnCredentialsByUserID :many
SELECT id, user_id, app_id, admin_id, credential_id, public_key,
       attestation_type, aaguid, sign_count, name, transports,
       backup_eligible, backup_state, last_used_at, created_at
FROM webauthn_credentials
WHERE user_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetWebAuthnCredentialsByUserID(ctx context.Context, userID pgtype.UUID) ([]WebauthnCredential, error) {
	rows, err := q.db.Query(ctx, getWebAuthnCredentialsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebauthnCredential{}
	for rows.Next() {
		var i WebauthnCredential
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AppID,
			&i.AdminID,
			&i.CredentialID,
			&i.PublicKey,
			&i.AttestationType,
			&i.Aaguid,
			&i.SignCount,
			&i.Name,
			&i.Transports,
			&i.BackupEligible,
			&i.BackupState,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameWebAuthnAdminCredential = `-- name: RenameWebAuthnAdminCredential :execrows
UPDATE webauthn_credentials
SET name = $3
WHERE id = $1 AND admin_id = $2
`

type RenameWebAuthnAdminCredentialParams struct {
	ID      uuid.UUID   `json:"id"`
	AdminID pgtype.UUID `json:"admin_id"`
	Name    *string     `json:"name"`
}

func (q *Queries) RenameWebAuthnAdminCredential(ctx context.Context, arg RenameWebAuthnAdminCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, renameWebAuthnAdminCredential, arg.ID, arg.AdminID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renameWebAuthnCredential = `-- name: RenameWebAuthnCredential :execrows
UPDATE webauthn_credentials
SET name = $3
WHERE id = $1 AND user_id = $2
`

type RenameWebAuthnCredentialParams struct {
	ID     uuid.UUID   `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
	Name   *string     `json:"name"`
}

func (q *Queries) RenameWebAuthnCredential(ctx context.Context, arg RenameWebAuthnCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, renameWebAuthnCredential, arg.ID, arg.UserID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateWebAuthnCredentialSignCount = `-- name: UpdateWebAuthnCredentialSignCount :exec
UPDATE webauthn_credentials
SET sign_count = $2, last_used_at = NOW()
WHERE id = $1
`

type UpdateWebAuthnCredentialSignCountParams struct {
	ID        uuid.UUID `json:"id"`
	SignCount int32     `json:"sign_count"`
}

func (q *Queries) UpdateWebAuthnCredentialSignCount(ctx context.Context, arg UpdateWebAuthnCredentialSignCountParams) error {
	_, err := q.db.Exec(ctx, updateWebAuthnCredentialSignCount, arg.ID, arg.SignCount)
	return err
}
