// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhook.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearWebhookRetrySchedule = `-- name: ClearWebhookRetrySchedule :exec
UPDATE webhook_deliveries
SET next_retry_at = NULL
WHERE id = $1
`

func (q *Queries) ClearWebhookRetrySchedule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearWebhookRetrySchedule, id)
	return err
}

const countAllWebhookEndpoints = `-- name: CountAllWebhookEndpoints :one
SELECT COUNT(*) FROM webhook_endpoints
WHERE deleted_at IS NULL
`

func (q *Queries) CountAllWebhookEndpoints(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllWebhookEndpoints)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWebhookDeliveriesByApp = `-- name: CountWebhookDeliveriesByApp :one
SELECT COUNT(*) FROM webhook_deliveries
WHERE app_id = $1
`

func (q *Queries) CountWebhookDeliveriesByApp(ctx context.Context, appID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWebhookDeliveriesByApp, appID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWebhookDeliveriesByEndpoint = `-- name: CountWebhookDeliveriesByEndpoint :one
SELECT COUNT(*) FROM webhook_deliveries
WHERE endpoint_id = $1
`

func (q *Queries) CountWebhookDeliveriesByEndpoint(ctx context.Context, endpointID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWebhookDeliveriesByEndpoint, endpointID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWebhookEndpointsByApp = `-- name: CountWebhookEndpointsByApp :one
SELECT COUNT(*) FROM webhook_endpoints
WHERE app_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountWebhookEndpointsByApp(ctx context.Context, appID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWebhookEndpointsByApp, appID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWebhookDelivery = `-- name: CreateWebhookDelivery :exec

INSERT INTO webhook_deliveries (id, endpoint_id, app_id, event_type, payload, attempt, status_code, response_body, latency_ms, success, error_message, next_retry_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type CreateWebhookDeliveryParams struct {
	ID           uuid.UUID          `json:"id"`
	EndpointID   uuid.UUID          `json:"endpoint_id"`
	AppID        uuid.UUID          `json:"app_id"`
	EventType    string             `json:"event_type"`
	Payload      string             `json:"payload"`
	Attempt      int32              `json:"attempt"`
	StatusCode   *int32             `json:"status_code"`
	ResponseBody *string            `json:"response_body"`
	LatencyMs    *int64             `json:"latency_ms"`
	Success      bool               `json:"success"`
	ErrorMessage *string            `json:"error_message"`
	NextRetryAt  pgtype.Timestamptz `json:"next_retry_at"`
	CreatedAt    time.Time          `json:"created_at"`
}

// ============================================================================
// Delivery operations
// ============================================================================
func (q *Queries) CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) error {
	_, err := q.db.Exec(ctx, createWebhookDelivery,
		arg.ID,
		arg.EndpointID,
		arg.AppID,
		arg.EventType,
		arg.Payload,
		arg.Attempt,
		arg.StatusCode,
		arg.ResponseBody,
		arg.LatencyMs,
		arg.Success,
		arg.ErrorMessage,
		arg.NextRetryAt,
		arg.CreatedAt,
	)
	return err
}

const createWebhookEndpoint = `-- name: CreateWebhookEndpoint :exec

INSERT INTO webhook_endpoints (id, app_id, event_type, url, secret, is_active, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateWebhookEndpointParams struct {
	ID        uuid.UUID `json:"id"`
	AppID     uuid.UUID `json:"app_id"`
	EventType string    `json:"event_type"`
	Url       string    `json:"url"`
	Secret    string    `json:"secret"`
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// ============================================================================
// Endpoint operations
// ============================================================================
func (q *Queries) CreateWebhookEndpoint(ctx context.Context, arg CreateWebhookEndpointParams) error {
	_, err := q.db.Exec(ctx, createWebhookEndpoint,
		arg.ID,
		arg.AppID,
		arg.EventType,
		arg.Url,
		arg.Secret,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getActiveWebhookEndpointsForEvent = `-- name: GetActiveWebhookEndpointsForEvent :many
SELECT id, app_id, event_type, url, secret, is_active, created_at, updated_at, deleted_at
FROM webhook_endpoints
WHERE app_id = $1 AND event_type = $2 AND is_active = true AND deleted_at IS NULL
`

type GetActiveWebhookEndpointsForEventParams struct {
	AppID     uuid.UUID `json:"app_id"`
	EventType string    `json:"event_type"`
}

func (q *Queries) GetActiveWebhookEndpointsForEvent(ctx context.Context, arg GetActiveWebhookEndpointsForEventParams) ([]WebhookEndpoint, error) {
	rows, err := q.db.Query(ctx, getActiveWebhookEndpointsForEvent, arg.AppID, arg.EventType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookEndpoint{}
	for rows.Next() {
		var i WebhookEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.EventType,
			&i.Url,
			&i.Secret,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingWebhookRetries = `-- name: GetPendingWebhookRetries :many
SELECT id, endpoint_id, app_id, event_type, payload, attempt, status_code, response_body, latency_ms, success, error_message, next_retry_at, created_at
FROM webhook_deliveries
WHERE success = false AND next_retry_at IS NOT NULL AND next_retry_at <= $1
ORDER BY next_retry_at ASC
LIMIT $2
`

type GetPendingWebhookRetriesParams struct {
	NextRetryAt pgtype.Timestamptz `json:"next_retry_at"`
	Limit       int32              `json:"limit"`
}

func (q *Queries) GetPendingWebhookRetries(ctx context.Context, arg GetPendingWebhookRetriesParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, getPendingWebhookRetries, arg.NextRetryAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.EndpointID,
			&i.AppID,
			&i.EventType,
			&i.Payload,
			&i.Attempt,
			&i.StatusCode,
			&i.ResponseBody,
			&i.LatencyMs,
			&i.Success,
			&i.ErrorMessage,
			&i.NextRetryAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWebhookEndpointByAppAndEvent = `-- name: GetWebhookEndpointByAppAndEvent :one
SELECT id, app_id, event_type, url, secret, is_active, created_at, updated_at, deleted_at
FROM webhook_endpoints
WHERE app_id = $1 AND event_type = $2 AND deleted_at IS NULL
`

type GetWebhookEndpointByAppAndEventParams struct {
	AppID     uuid.UUID `json:"app_id"`
	EventType string    `json:"event_type"`
}

func (q *Queries) GetWebhookEndpointByAppAndEvent(ctx context.Context, arg GetWebhookEndpointByAppAndEventParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, getWebhookEndpointByAppAndEvent, arg.AppID, arg.EventType)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.EventType,
		&i.Url,
		&i.Secret,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWebhookEndpointByID = `-- name: GetWebhookEndpointByID :one
SELECT id, app_id, event_type, url, secret, is_active, created_at, updated_at, deleted_at
FROM webhook_endpoints
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetWebhookEndpointByID(ctx context.Context, id uuid.UUID) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, getWebhookEndpointByID, id)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.EventType,
		&i.Url,
		&i.Secret,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAllWebhookEndpoints = `-- name: ListAllWebhookEndpoints :many
SELECT id, app_id, event_type, url, secret, is_active, created_at, updated_at, deleted_at
FROM webhook_endpoints
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllWebhookEndpointsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllWebhookEndpoints(ctx context.Context, arg ListAllWebhookEndpointsParams) ([]WebhookEndpoint, error) {
	rows, err := q.db.Query(ctx, listAllWebhookEndpoints, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookEndpoint{}
	for rows.Next() {
		var i WebhookEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.EventType,
			&i.Url,
			&i.Secret,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookDeliveriesByApp = `-- name: ListWebhookDeliveriesByApp :many
SELECT id, endpoint_id, app_id, event_type, payload, attempt, status_code, response_body, latency_ms, success, error_message, next_retry_at, created_at
FROM webhook_deliveries
WHERE app_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListWebhookDeliveriesByAppParams struct {
	AppID  uuid.UUID `json:"app_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListWebhookDeliveriesByApp(ctx context.Context, arg ListWebhookDeliveriesByAppParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveriesByApp, arg.AppID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.EndpointID,
			&i.AppID,
			&i.EventType,
			&i.Payload,
			&i.Attempt,
			&i.StatusCode,
			&i.ResponseBody,
			&i.LatencyMs,
			&i.Success,
			&i.ErrorMessage,
			&i.NextRetryAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookDeliveriesByEndpoint = `-- name: ListWebhookDeliveriesByEndpoint :many
SELECT id, endpoint_id, app_id, event_type, payload, attempt, status_code, response_body, latency_ms, success, error_message, next_retry_at, created_at
FROM webhook_deliveries
WHERE endpoint_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListWebhookDeliveriesByEndpointParams struct {
	EndpointID uuid.UUID `json:"endpoint_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListWebhookDeliveriesByEndpoint(ctx context.Context, arg ListWebhookDeliveriesByEndpointParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveriesByEndpoint, arg.EndpointID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.EndpointID,
			&i.AppID,
			&i.EventType,
			&i.Payload,
			&i.Attempt,
			&i.StatusCode,
			&i.ResponseBody,
			&i.LatencyMs,
			&i.Success,
			&i.ErrorMessage,
			&i.NextRetryAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookEndpointsByApp = `-- name: ListWebhookEndpointsByApp :many
SELECT id, app_id, event_type, url, secret, is_active, created_at, updated_at, deleted_at
FROM webhook_endpoints
WHERE app_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListWebhookEndpointsByAppParams struct {
	AppID  uuid.UUID `json:"app_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListWebhookEndpointsByApp(ctx context.Context, arg ListWebhookEndpointsByAppParams) ([]WebhookEndpoint, error) {
	rows, err := q.db.Query(ctx, listWebhookEndpointsByApp, arg.AppID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookEndpoint{}
	for rows.Next() {
		var i WebhookEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.EventType,
			&i.Url,
			&i.Secret,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteWebhookEndpoint = `-- name: SoftDeleteWebhookEndpoint :exec
UPDATE webhook_endpoints
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteWebhookEndpoint(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteWebhookEndpoint, id)
	return err
}

const updateWebhookEndpointActive = `-- name: UpdateWebhookEndpointActive :exec
UPDATE webhook_endpoints
SET is_active = $2
WHERE id = $1
`

type UpdateWebhookEndpointActiveParams struct {
	ID       uuid.UUID `json:"id"`
	IsActive bool      `json:"is_active"`
}

func (q *Queries) UpdateWebhookEndpointActive(ctx context.Context, arg UpdateWebhookEndpointActiveParams) error {
	_, err := q.db.Exec(ctx, updateWebhookEndpointActive, arg.ID, arg.IsActive)
	return err
}
