package main

import (
	"fmt"
	"log"
	"os"
	"strings"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/joho/godotenv"

	core "github.com/MrF1ow/go-core"
	"github.com/MrF1ow/go-core/app"

	_ "github.com/MrF1ow/go-core/docs" // docs is generated by Swag CLI
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title           Authentication and Authorization API
// @version         1.1.0
// @description     This is a sample authentication and authorization API built with Go and Gin.
// @termsOfService  http://swagger.io/terms/

// @contact.name   API Support
// @contact.url    http://www.swagger.io/support
// @contact.email  support@swagger.io

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

// @host      localhost:8080
// @BasePath  /

// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name Authorization
// @description Type "Bearer" + your JWT token

// @securityDefinitions.apikey AppID
// @in header
// @name X-App-ID
// @description The UUID of the application context

// @securityDefinitions.apikey AdminApiKey
// @in header
// @name X-Admin-API-Key
// @description Admin API Key for protected admin routes

// @securityDefinitions.apikey AppApiKey
// @in header
// @name X-App-API-Key
// @description Per-application API Key for app-scoped routes

// envStr reads an environment variable with a fallback default.
func envStr(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}

// envInt reads an integer environment variable with a fallback default.
func envInt(key string, fallback int) int {
	if v := os.Getenv(key); v != "" {
		var n int
		if _, err := fmt.Sscanf(v, "%d", &n); err == nil {
			return n
		}
	}
	return fallback
}

// envBool reads a boolean environment variable with a fallback default.
func envBool(key string, fallback bool) bool {
	v := os.Getenv(key)
	switch strings.ToLower(v) {
	case "true", "1", "yes":
		return true
	case "false", "0", "no":
		return false
	default:
		return fallback
	}
}

// envDuration reads a duration environment variable with a fallback default.
func envDuration(key string, fallback time.Duration) time.Duration {
	if v := os.Getenv(key); v != "" {
		if d, err := time.ParseDuration(v); err == nil {
			return d
		}
	}
	return fallback
}

// splitTrimmed splits a comma-separated string and trims whitespace, filtering empty entries.
func splitTrimmed(s string) []string {
	parts := strings.Split(s, ",")
	out := make([]string, 0, len(parts))
	for _, p := range parts {
		if v := strings.TrimSpace(p); v != "" {
			out = append(out, v)
		}
	}
	return out
}

func main() {
	// Load environment variables from .env file
	if err := godotenv.Load(); err != nil {
		log.Println("No .env file found, relying on environment variables")
	}

	// Build configuration from environment variables
	cfg := core.Config{
		Database: core.DatabaseConfig{
			Host:     envStr("DB_HOST", "localhost"),
			Port:     envInt("DB_PORT", 5432),
			User:     envStr("DB_USER", "postgres"),
			Password: os.Getenv("DB_PASSWORD"),
			DBName:   envStr("DB_NAME", "go_core"),
			SSLMode:  envStr("DB_SSLMODE", "disable"),
		},
		Redis: &core.RedisConfig{
			Addr:     envStr("REDIS_ADDR", "localhost:6379"),
			Password: os.Getenv("REDIS_PASSWORD"),
			DB:       envInt("REDIS_DB", 1),
		},
		JWT: core.JWTConfig{
			Secret:          os.Getenv("JWT_SECRET"),
			AccessTokenTTL:  time.Duration(envInt("ACCESS_TOKEN_EXPIRATION_MINUTES", 15)) * time.Minute,
			RefreshTokenTTL: time.Duration(envInt("REFRESH_TOKEN_EXPIRATION_HOURS", 720)) * time.Hour,
		},
		CORS: core.CORSConfig{
			AllowedOrigins:   splitTrimmed(envStr("CORS_ALLOWED_ORIGINS", "http://localhost:3000,http://localhost:5173,http://localhost:5174,http://localhost:5175,http://localhost:8080")),
			AllowedMethods:   splitTrimmed(envStr("CORS_ALLOWED_METHODS", "GET,POST,PUT,DELETE,OPTIONS,HEAD")),
			AllowedHeaders:   splitTrimmed(envStr("CORS_ALLOWED_HEADERS", "Origin,Content-Type,Content-Length,Accept-Encoding,X-CSRF-Token,Authorization,Accept,Cache-Control,X-Requested-With,X-App-ID")),
			ExposeHeaders:    splitTrimmed(envStr("CORS_EXPOSE_HEADERS", "Content-Length,Access-Control-Allow-Origin,Access-Control-Allow-Headers,Content-Type")),
			MaxAge:           time.Duration(envInt("CORS_MAX_AGE_HOURS", 12)) * time.Hour,
			AllowCredentials: envBool("CORS_ALLOW_CREDENTIALS", true),
		},
		OIDC: core.OIDCConfig{
			Enabled:      envBool("OIDC_ENABLED", false),
			DefaultAppID: envStr("OIDC_DEFAULT_APP_ID", "00000000-0000-0000-0000-000000000001"),
			IDTokenTTL:   time.Duration(envInt("OIDC_ID_TOKEN_EXPIRATION_MINUTES", 60)) * time.Minute,
			AuthCodeTTL:  time.Duration(envInt("OIDC_AUTH_CODE_EXPIRATION_MINUTES", 10)) * time.Minute,
		},
		WebAuthn: core.WebAuthnConfig{
			RPID:      os.Getenv("WEBAUTHN_RP_ID"),
			RPName:    os.Getenv("WEBAUTHN_RP_NAME"),
			RPOrigins: splitTrimmed(os.Getenv("WEBAUTHN_RP_ORIGINS")),
		},
		SMS: core.SMSConfig{
			Provider:         os.Getenv("SMS_PROVIDER"),
			TwilioAccountSID: os.Getenv("SMS_TWILIO_ACCOUNT_SID"),
			TwilioAuthToken:  os.Getenv("SMS_TWILIO_AUTH_TOKEN"),
			TwilioFromNumber: os.Getenv("SMS_TWILIO_FROM_NUMBER"),
		},
		Admin: core.AdminConfig{
			APIKey:        os.Getenv("ADMIN_API_KEY"),
			Email:         os.Getenv("ADMIN_EMAIL"),
			SessionTTL:    time.Duration(envInt("ADMIN_SESSION_EXPIRATION_HOURS", 8)) * time.Hour,
			BaseURL:       os.Getenv("ADMIN_BASE_URL"),
			AdminBasePath: envStr("ADMIN_BASE_PATH", "/gui"),
			Branding: core.AdminBrandingConfig{
				OrgName:          os.Getenv("ADMIN_BRANDING_ORG_NAME"),
				LogoURL:          os.Getenv("ADMIN_BRANDING_LOGO_URL"),
				PrimaryColor:     os.Getenv("ADMIN_BRANDING_PRIMARY_COLOR"),
				SecondaryColor:   os.Getenv("ADMIN_BRANDING_SECONDARY_COLOR"),
				BorderRadius:     os.Getenv("ADMIN_BRANDING_BORDER_RADIUS"),
				SidebarColor:     os.Getenv("ADMIN_BRANDING_SIDEBAR_COLOR"),
				SidebarTextColor: os.Getenv("ADMIN_BRANDING_SIDEBAR_TEXT_COLOR"),
			},
		},
		Social: core.SocialConfig{
			AllowedRedirectDomains: splitTrimmed(os.Getenv("ALLOWED_REDIRECT_DOMAINS")),
			DefaultRedirectURI:     os.Getenv("DEFAULT_REDIRECT_URI"),
		},
		GeoIP: core.GeoIPConfig{
			DBPath: os.Getenv("GEOIP_DB_PATH"),
		},
		Session: core.SessionConfig{
			TrustedDeviceCookieSameSite: envStr("TRUSTED_DEVICE_COOKIE_SAMESITE", "none"),
			GroupExpiryEnabled:          envBool("SESSION_GROUP_EXPIRY_REVOCATION_ENABLED", false),
			GroupExpiryScanInterval:     envDuration("SESSION_GROUP_EXPIRY_SCAN_INTERVAL", 5*time.Minute),
			GroupKeyspaceNotifEnabled:   envBool("SESSION_GROUP_KEYSPACE_NOTIF_ENABLED", false),
			RedisNotifyKeyspaceEvents:   os.Getenv("REDIS_NOTIFY_KEYSPACE_EVENTS"),
		},
		MultiTenant: envBool("MULTI_TENANT", false),
		PublicURL:   envStr("PUBLIC_URL", "http://localhost:8080"),
		FrontendURL: envStr("FRONTEND_URL", "http://localhost:5173"),
		AppName:     os.Getenv("APP_NAME"),
		Port:        envStr("PORT", "8080"),
		GinMode:     envStr("GIN_MODE", "debug"),
	}

	coreApp, err := app.New(cfg)
	if err != nil {
		log.Fatalf("Failed to initialize: %v", err)
	}
	defer coreApp.Close()

	gin.SetMode(cfg.GinMode)
	r := gin.Default()

	// Register all core routes
	coreApp.RegisterRoutes(r)

	// Add Swagger UI endpoint (only in the reference app, not in core)
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Start the server
	log.Printf("Server starting on port %s", cfg.Port)
	if err := r.Run(fmt.Sprintf(":%s", cfg.Port)); err != nil {
		log.Fatalf("Server failed to start: %v", err)
	}
}
